NeuralMAB
aimclub/GOLEM pull request #102
Opened 2023-05-22 13:57 UTC by maypink

WIP

2023-05-26 06:29 UTC, gkirgizov requested changes
Все выглядит разумно, вопросов по реализации нет, есть вопросы и комментарии по логике.

- Сориентируй, как долго работает энкодер на графах? Сколько занимает итерация обучения нейронки?
- Тестировала ли ты реализацию бандита на какой-то простой задаче? Бенчмарк из статьи, например. Можно без энкодера графов обойтись.
- Нужно поставить эксперимент, где для разных графов (разных эмбеддингов) наилучшими будут различные действия. Например, если это оптимизация размера графов до N , то маленькие графы надо растить, а большие обрезать. Вот надо бы хотя бы такой тривиальный случай поймать, чтобы проверить , что контекст вообще работает. И затем что-то менее тривиальное надо придумать.

2023-05-26 06:29 UTC, gkirgizov commented on golem/core/optimisers/adaptive/neural_mab.py
> +        self.nn_with_se = NNWithShallowExploration(context_size=500, arms_count=len(arms))
А здешний `context_size` ты тоже обрезала до 20 при попытке сократить время? Вижу только двадцатку выше, в энкодере

2023-05-26 06:29 UTC, gkirgizov commented on golem/core/optimisers/adaptive/neural_mab.py
> +        self._mab.fit(decisions=self._indices, rewards=uniform_rewards, contexts=n * [deep_context])
Предлагаю убрать этот обман бедного бандита с произвольным контекстом. Вместо этого использовать флаг is_fitted внутри partial_fit для первого фита

2023-05-26 06:29 UTC, gkirgizov commented on golem/core/optimisers/adaptive/neural_mab.py
> +                    decisions: List[Any], rewards: List[float], contexts: List[Any] = None):
Можешь пояснить этот кусок? Мы обучаемся раз в H итераций оптимизатора? Мы каждую итерацию что-то делаем?

2023-05-26 06:29 UTC, gkirgizov commented on golem/core/optimisers/adaptive/neural_mab.py
> +class NNWithShallowExploration:
Это твоя реализация или она взята откуда-то?

2023-05-29 09:30 UTC, maypink commented on golem/core/adapter/nx_adapter.py
> +class BanditNetworkxAdapter(BaseNetworkxAdapter):
Потому что с обычным адаптером там в качестве имен нод в nx.Graph определеляется uid из големовского графа =>в karateclub(откуда импортируется класс для получения эмбеддингов) есть проверка, которая не проходит из-за этого
![image](https://github.com/aimclub/GOLEM/assets/57305249/e83da568-8d5a-4123-b8b1-aa4e52dc1366)

2023-05-29 09:31 UTC, maypink commented on golem/core/optimisers/adaptive/neural_mab.py
> +        self.nn_with_se = NNWithShallowExploration(context_size=500, arms_count=len(arms))
не, обрезала везде, там же иначе просто матрицы не перемножатся из-за несовпадения размерностей. это я скорее 20 забыла убрать

2023-05-29 09:56 UTC, maypink commented on golem/core/optimisers/adaptive/neural_mab.py
> +                    decisions: List[Any], rewards: List[float], contexts: List[Any] = None):
обучаемся и обновляем веса раз в _H_q (сейчас 5) итераций, но каждую итерацию подсчитываем текущий reward и собираем датасет для следующего дообучения (в context_action и reward_action)

2023-05-29 09:57 UTC, maypink commented on golem/core/optimisers/adaptive/neural_mab.py
> +class NNWithShallowExploration:
нейронка взята с supplementary материалов к этой статье, с open review

2023-05-29 10:03 UTC, maypink commented on golem/core/optimisers/adaptive/neural_contextual_mab_agent.py
> +        context_agent = ContextAgentsRepository.agent_class_by_id(self._context_agent)
[done](https://github.com/aimclub/GOLEM/pull/102/commits/9893a281cfb8f2ae9ad06f866f3a7ecdb710be75#diff-ce10550c5a8aaaf09d20512132eab2b49192b96b1072a68e0a3b088c4635abd4R23)

2023-05-29 10:10 UTC, maypink commented on golem/core/optimisers/adaptive/neural_mab.py
> +        self._mab.fit(decisions=self._indices, rewards=uniform_rewards, contexts=n * [deep_context])
не совсем поняла, при чем тут первый фит. проблема же в том, что predict вызывается первее, чем partial_fit, так что нужен какой-то warm start

2023-05-29 10:24 UTC, gkirgizov commented on golem/core/adapter/nx_adapter.py
> +class BanditNetworkxAdapter(BaseNetworkxAdapter):
И зачем им это нужно... 
Добавь где-нибудь комментарий с обоснованием, пожалуйста

2023-05-29 10:25 UTC, gkirgizov commented on golem/core/optimisers/adaptive/neural_mab.py
> +        self._mab.fit(decisions=self._indices, rewards=uniform_rewards, contexts=n * [deep_context])
может, тогда в predict добавить проверку на is_fitted? и выдавать дефолтные вероятности, что-то такое

2023-05-29 10:26 UTC, gkirgizov commented on golem/core/optimisers/adaptive/neural_mab.py
> +                    decisions: List[Any], rewards: List[float], contexts: List[Any] = None):
Понял, спасибо. Добавь, пожалуйста, это где-нибудь в комментарий. Позволяет быстрее разобраться в логике

2023-05-29 10:27 UTC, gkirgizov commented on golem/core/optimisers/adaptive/neural_mab.py
> +class NNWithShallowExploration:
оо, понял о чем ты говорила про кучу кода в статье. Нет бы им по-человечески залить на гитхаб. Хитрые ребята в  этом DeepMind, явно что-то скрывают

2023-05-29 12:33 UTC, maypink commented on golem/core/optimisers/adaptive/neural_mab.py
> +        self._mab.fit(decisions=self._indices, rewards=uniform_rewards, contexts=n * [deep_context])
да будто бы это оно и есть. мы же одинаковый контекст с одинаковыми наградами передаем для всех рук, то есть вероятности не сдвинутся после такого

2023-05-29 12:35 UTC, maypink commented on golem/core/adapter/nx_adapter.py
> +class BanditNetworkxAdapter(BaseNetworkxAdapter):
[done](https://github.com/aimclub/GOLEM/pull/102/commits/22d3305886c1fbcd6573cb11ae51860ab33cce81#diff-78c47341b9a2c95965f9d7f4c138d331ac0ae6b60c8934fbfeb447e20c836433R90)

2023-05-29 12:36 UTC, maypink commented on golem/core/optimisers/adaptive/neural_mab.py
> +                    decisions: List[Any], rewards: List[float], contexts: List[Any] = None):
[done](https://github.com/aimclub/GOLEM/pull/102/commits/9893a281cfb8f2ae9ad06f866f3a7ecdb710be75#diff-58861d15f7642ee0468b2f3423ffdc145f0af1f3c10e7fdd5f093375990f732cR57)

2023-05-29 12:37 UTC, maypink commented on golem/core/optimisers/adaptive/neural_mab.py
> +class NNWithShallowExploration:
да спасибо, что хоть так выложили

2023-06-07 04:48 UTC, gkirgizov commented on golem/core/optimisers/adaptive/neural_mab.py
> +        self._mab.fit(decisions=self._indices, rewards=uniform_rewards, contexts=n * [deep_context])
Мы вносим bias , давая бандиту ложные данные. Это не очень корректно, больше на хак похоже.

2023-06-07 05:28 UTC, gkirgizov requested changes

2023-06-07 05:28 UTC, gkirgizov commented on examples/adaptive_optimizer/experiment_setup.py
> +                stats_action_value_log[i] = (list(values))
Классная мысль использовать KMeans для этого

2023-06-07 05:28 UTC, gkirgizov commented on examples/adaptive_optimizer/mab_experiment_different_targets.py
> +            graph_size=[random.randint(5, 10) for _ in range(19)] + [random.randint(90, 95) for _ in range(2)]
Предлгааю тут разделить поровну общий pop_size

2023-06-07 05:28 UTC, gkirgizov commented on examples/synthetic_graph_evolution/graph_search.py
> +                       graph_size: Optional[List[int]] = None,
Предлагаю переименовать в `initial_graph_sizes` для очевидности

2023-06-07 05:28 UTC, gkirgizov commented on experiments/mab/mab_synthetic_experiment_helper.py
> +            optimizer.set_iteration_callback(log_action_values_with_clusters)
Добавь лучше явное условие. А то при запуске, например, на `default` vs `bandit` получим что-то не то

2023-06-07 05:28 UTC, gkirgizov commented on experiments/mab/mab_synthetic_experiment_helper.py
> +                                           actions=agent.actions)
Дело вкуса, пожалуй, но я вижу роль kwargs в 3 случаях: когда мы указываем доп. параметры, когда мы меняем порядок аргументов по каким-то своим причинам, или когда это улучшает читаемость (например, `range(start=42, end=99)`). В данном случае, по мне, как-то избыточно

2023-06-07 05:28 UTC, gkirgizov commented on experiments/mab/mab_synthetic_experiment_helper.py
> +                            total_sum[cluster][i][j] += launch[cluster][i][j]
о, впервые вижу вложенный цикл глубины 5 )
(этот комент действий не требует)

2023-06-07 05:28 UTC, gkirgizov commented on requirements.txt
> +mabwiser~=2.7.0
Перенеси этого mabwiser к остальным зависимостям бандитов и, пожалуй, вынеси эти зависимости вместе с PyTorch в какой-нибудь отдельный requirements-adaptive. Это пока экспериментальная функциональность и не хочется ее зависимостями утяжелять ГОЛЕМ. Тем более только избавились в дочернем ФЕДОТе от тяжелых зависимостей в основном файле.

2023-06-09 07:05 UTC, maypink commented on experiments/mab/mab_synthetic_experiment_helper.py
> +                                           actions=agent.actions)
у меня просто было пару случаев, когда аргументы путались между собой из-за отсутствия четкого сопоставления, поэтому я все-таки за однозначную определенность здесь

2023-06-09 07:20 UTC, maypink commented on examples/adaptive_optimizer/mab_experiment_different_targets.py
> +            graph_size=[random.randint(5, 10) for _ in range(19)] + [random.randint(90, 95) for _ in range(2)]
[done](https://github.com/aimclub/GOLEM/pull/102/commits/6446b72435833b425563dfff5cb2cc7656b22a2d#diff-7604b6987015309112ebfa7a33971f563b35424111e458867f4dee965c9a7417L72), убрала вообще, а то там твоя постановка задачи была, а я сверху поэкспериментировала

2023-06-09 07:21 UTC, maypink commented on examples/synthetic_graph_evolution/graph_search.py
> +                       graph_size: Optional[List[int]] = None,
[done](https://github.com/aimclub/GOLEM/pull/102/commits/6446b72435833b425563dfff5cb2cc7656b22a2d#diff-689a685e451a5f79c85eb2586f23af951f3ac75335d4b6aae2e5408a5619c339R29)

2023-06-09 07:21 UTC, maypink commented on experiments/mab/mab_synthetic_experiment_helper.py
> +            optimizer.set_iteration_callback(log_action_values_with_clusters)
[done](https://github.com/aimclub/GOLEM/pull/102/commits/6446b72435833b425563dfff5cb2cc7656b22a2d#diff-b6cf9baf15bb8280215954f2c5c9321bacb8f545dc267a54f81737e75bddc17eR84)

2023-06-09 07:21 UTC, maypink commented on requirements.txt
> +mabwiser~=2.7.0
[done](https://github.com/aimclub/GOLEM/pull/102/commits/6446b72435833b425563dfff5cb2cc7656b22a2d#diff-5f60f4ecdeaa9f75e989fa3070db7af8805dbde78d7386e6259467d96127a185R1)

2023-06-09 08:02 UTC, maypink commented on golem/core/optimisers/adaptive/neural_mab.py
> +        self._mab.fit(decisions=self._indices, rewards=uniform_rewards, contexts=n * [deep_context])
да вроде не можем: у бандитов есть warm_start, но он предназначен не для этого, а для того, чтобы просто задать начальное представление перед первым фитом. без фита все равно не обойтись

2023-06-09 09:53 UTC, gkirgizov approved these changes

2023-06-09 11:14 UTC, merged