Add new plots for population Diversity
aimclub/GOLEM pull request #113
Opened 2023-06-06 08:29 UTC by gkirgizov

Add 2 new kinds of plot for estimating diversity of populations based on OptHistory.
Done as additional functionality during work on #89 

Usage example:
```
TODO
```

2 examples: 
- static plot howing diversity during optimization;
- GIF plot showing metric distribution per each metric in population

![Diversity plot](https://github.com/aimclub/GOLEM/assets/10994117/66ae68af-54c5-4176-a57e-b2c7f5866482)

![Diveristy GIF](https://github.com/aimclub/GOLEM/assets/10994117/b0687c04-b37e-42ea-aad0-8758f17e007d)

2023-06-06 09:14 UTC, MorrisNein commented
Отлично, больше доступных визуализаций всегда лучше, чем меньше. Подскажи, diversity всегда измеряешь как разнообразие значений в используемой метрике? Оценивается ли разнообразие состава узлов графа?

2023-06-06 09:17 UTC, nicl-nno commented
А в структурах проверяется только полное совпадение? Может добавить что-то вроде распределения попарных расстояний между графами?

2023-06-07 04:32 UTC, gkirgizov commented
> Отлично, больше доступных визуализаций всегда лучше, чем меньше. Подскажи, diversity всегда измеряешь как разнообразие значений в используемой метрике? Оценивается ли разнообразие состава узлов графа?

И то,  и другое.
В основном, разнообразие по метрикам. Дополнительно -- доля*структурно* уникальных индивидов, сравнивается через `__eq__`

2023-06-07 04:37 UTC, gkirgizov commented
> А в структурах проверяется только полное совпадение? Может добавить что-то вроде распределения попарных расстояний между графами?

Да, полное. Можно добавить такое распределение, пожалуй.  Попробую

2023-06-07 07:58 UTC, nicl-nno commented
>edit distance между графами и так может по минуте считаться

Может сделать какую-то приближенную оценку? Сравнивать хотя бы совпадение вектора вершин и вектора ребер.

В стиле "0 - совпадают полностью, различаются гиперпараметры - плюс <число различающихся вершин>, различаются типы моделей - плюс<число различающихся вершин>, различаются ребра (в предположении что ребро это пара вершин) - плюс число ребер. 

Чтобы было проще отлавливать ситуации, когда различия есть, но около-минимальны.

2023-06-07 07:59 UTC, nicl-nno approved these changes

2023-06-07 12:27 UTC, MorrisNein requested changes
Небольшое пожелание: две шкалы это удобно, но глаза теряются. Предлагаю немного поразмыслить, каким образом визуально выделить показатель для правой шкалы. Пока в голову приходит отрисовка его пунктиром или проекции от линии на соответствующую ось

2023-06-07 12:27 UTC, MorrisNein commented on golem/visualisation/opt_history/diversity.py
> +    ax2.set_ylim(0.25, 1.05)
Нижняя граница определена опытным путём? Может ли не хватить для какой-то истории?

2023-06-07 12:27 UTC, MorrisNein commented on golem/visualisation/opt_history/diversity.py
> +        return plot_diversity_dynamic_gif(self.history, filename=save_path, fps=fps, dpi=self.visuals_params['dpi'])
Добавь, пожалуйста, докстринги - методам visualize. Для diversity line были сомнения, как его читать, пока не залез в код.

2023-06-07 12:27 UTC, MorrisNein commented on golem/visualisation/opt_history/diversity.py
> +    ax2.plot(xs, ratio_unique, label='unique ratio', color='tab:gray')
Для того, чтобы линии не закрывали друг друга на пересечениях, предлагаю задать alpha>1.

2023-06-07 12:46 UTC, MorrisNein commented
> Небольшое пожелание: две шкалы это удобно, но глаза теряются. Предлагаю немного поразмыслить, каким образом визуально выделить показатель для правой шкалы. Пока в голову приходит отрисовка его пунктиром или проекции от линии на соответствующую ось.
> 
> Если выйдет запарно/некрасиво, то пусть будет как есть

Можно, например, сделать цветную подпись у правой шкалы, как в [этом примере](https://matplotlib.org/stable/gallery/subplots_axes_and_figures/two_scales.html)

2023-06-08 05:05 UTC, gkirgizov commented on golem/visualisation/opt_history/diversity.py
> +    ax2.set_ylim(0.25, 1.05)
Не совсем. Смысл скорее в том, что ниже четверти уникальных уже бессмысленно как-то оценивать. То есть это плоо и это и так понятно

2023-06-08 05:08 UTC, gkirgizov commented on golem/visualisation/opt_history/diversity.py
> +    ax2.set_ylim(0.25, 1.05)
Плюс этого решения в том, что легче и интуитивнее сравнивать два разных графика, т.к. у них одна фиксированная граница

2023-06-08 05:22 UTC, gkirgizov commented on golem/visualisation/opt_history/diversity.py
> +        return plot_diversity_dynamic_gif(self.history, filename=save_path, fps=fps, dpi=self.visuals_params['dpi'])
Добавил комменты

2023-06-08 05:34 UTC, gkirgizov commented
> Можно, например, сделать цветную подпись у правой шкалы, как в [этом примере](https://matplotlib.org/stable/gallery/subplots_axes_and_figures/two_scales.html)

Цветовая ассоциация полезна, да. Вот обновленный вариант с более понятными подпиясми осей к тому же.

![Figure_3-v2](https://github.com/aimclub/GOLEM/assets/10994117/f7a58352-8ab8-4ace-b879-a906b4eb2b6b)

2023-06-08 06:38 UTC, MorrisNein approved these changes

2023-06-08 07:19 UTC, merged