Custom operator serialize
aimclub/GOLEM pull request #120
Opened 2023-06-13 14:13 UTC by YamLyubov

WIP

2023-06-20 07:28 UTC, gkirgizov requested changes

2023-06-20 07:28 UTC, gkirgizov commented on golem/serializers/coders/graph_serialization.py
> +                    node.nodes_from[parent_node_idx] = lookup_dict.get(parent_node_uid, None)
Может, тут получится сократить дублирование кода?

2023-06-20 07:28 UTC, gkirgizov commented on test/unit/serialization/test_external_serialize.py
> +    assert len(history.individuals) > 0
Может, сделать еще проверку на то, что внутри индивида находитс нечто разумное? Либо граф либо словарь, в зависимости от ситуации

2023-06-20 07:29 UTC, gkirgizov commented
> This visualization works with one line correction in FEDOT.Web code

Сделаешь PR туда с этим микрофиксом?

2023-06-20 07:30 UTC, gkirgizov commented on test/unit/serialization/test_external_serialize.py
> +    assert len(history.individuals) > 0
И можно еще сделать тест на то, что визуализации истории не падают

2023-06-20 12:35 UTC, YamLyubov commented on test/unit/serialization/dataclasses_serialisation/serialization_dataclasses.py
Убрала папку

2023-06-20 12:36 UTC, YamLyubov commented on golem/serializers/coders/graph_serialization.py
> +                    node.nodes_from[parent_node_idx] = lookup_dict.get(parent_node_uid, None)
[Действительно](https://github.com/aimclub/GOLEM/pull/120/files?diff=unified&w=0#diff-d0f033a6715bf9fd47fa8a25226e93fd86b2ac42c7df5edfceefa5d04971a8d3R30-R39)

2023-06-20 12:37 UTC, YamLyubov commented on test/unit/serialization/test_external_serialize.py
> +    assert len(history.individuals) > 0
Проверка структуры загруженной истории: https://github.com/aimclub/GOLEM/pull/120/files?diff=unified&w=0#diff-95de3bae2a8abb8bc2f8cfabfa83e3ec519729ff70b61be6177a3c66977edfb9R37-R58

Проверка визуализаций (долго проходит, поэтому в интеграционных): https://github.com/aimclub/GOLEM/pull/120/files?diff=unified&w=0#diff-66c9537f426e7fc9b71d7055e1d26b9067cb8634ee1caf965ea673e00d8bfeb1

2023-06-21 11:16 UTC, MorrisNein requested changes
С одной стороны, удобно, а с другой, я не понял, какую проблему это устраняет

Вообще, как будто это эффективно прячет из вида проблемы обратной совместимости истории

По реализации небольшой вопрос + правка по стилю, в остальном всё норм

2023-06-21 11:16 UTC, MorrisNein commented on golem/serializers/serializer.py
>              if isclass(obj_cls) and base_type is not None:
Место выглядит немного запутанным с точки зрения логики. Новый метод serialize_as_base_class действительно требует новой логики инициализации? Или можно вернуть нужный base_class из get_class, а дальнейшую логику сериализации оставить прежней?

К примеру, если я не ошибаюсь, для нового способа десериализации из атрибутов объекта не удаляется путь к классу

2023-06-21 12:00 UTC, MorrisNein commented
В общем, @YamLyubov, напиши кратко, как это используется, в описание PR, пожалуйста! Либо ссылку на issue, если такая есть

2023-06-26 11:56 UTC, MorrisNein requested changes

2023-06-26 11:56 UTC, MorrisNein commented on golem/serializers/serializer.py
> +            return Serializer._import_as_base_class(json_obj, ex)
Предлагаю вынести цикл и return из-под проверки

Мотивация: проверка может спрятать исключение там, где это не нужно (будет актуально, если сюда ещё навалят кода)

2023-06-26 11:56 UTC, MorrisNein commented on golem/serializers/serializer.py
> +            return Serializer._import_as_base_class(json_obj, ex)
Рассматривала вариант логировать ImportError прямо здесь, воспользовавшись вернувшимся классом и не передавая исключение?

2023-06-27 08:51 UTC, YamLyubov commented on golem/serializers/serializer.py
> +            return Serializer._import_as_base_class(json_obj, ex)
Кажется  так действительно лучше стало

2023-06-27 10:45 UTC, MorrisNein approved these changes

2023-06-27 10:45 UTC, MorrisNein commented on golem/serializers/serializer.py
> +            return obj_cls
Кажется, ветки условия перепутаны 

И ещё, вызов `.__class__` от переменной-класса избыточен?

2023-06-28 10:50 UTC, merged