Encodings for graphs
aimclub/GOLEM pull request #129
Opened 2023-06-19 12:09 UTC by maypink

WIP

2023-06-26 13:36 UTC, gkirgizov requested changes
Пробовала что-нибудь запускать с этими способами кодирования?

2023-06-26 13:36 UTC, gkirgizov commented on experiments/mab/mab_synthetic_experiment_helper.py
> +            # opt_graph.update_node(old_node=node, new_node=OptNode('x', nodes_from=node.nodes_from))
Забыла код под комментом?

2023-06-26 13:36 UTC, gkirgizov commented on experiments/mab/mab_synthetic_experiment_helper.py
> +            node.content['name'] = 'x'
Вот, кажется, такие штуки тяжело будет ловить, тяжело избегать и невозможно запретить при учете изменений с кэшированием descriptive_id

2023-06-26 13:36 UTC, gkirgizov commented on experiments/mab/mab_synthetic_experiment_helper.py
> +
Опиши где-нибудь в комментах, пожалуйста, как соотносятся `context_agent_types` & `bandits_to_compare`. Что с чем сравнивается в итоге?

2023-06-26 13:36 UTC, gkirgizov commented on golem/core/optimisers/adaptive/context_agents.py
> +    :param mode: mode of encoding. Available type: 'ohe' and 'label', default -- 'label'
что значит `ohe`?)

2023-06-26 13:36 UTC, gkirgizov commented on golem/core/optimisers/adaptive/context_agents.py
> +    return encode_operations(operations=operations, available_operations=available_operations)
А при чем здесь ребра? Не очень понимаю назначение этой функции

2023-06-26 13:36 UTC, gkirgizov commented on golem/core/optimisers/adaptive/context_agents.py
> +def operations_encoding(obs: Any, available_operations: List[str]) -> List[int]:
Чем отличается функция `operations_encoding` от `encode_operations`? По названию не отличить

2023-06-26 13:36 UTC, gkirgizov commented on golem/core/optimisers/adaptive/mab_agents/contextual_mab_agent.py
> +                contexts.append(self._context_agent(ob))
А такое бывает? Почему ты добавила этот if?

2023-06-27 12:12 UTC, maypink commented on experiments/mab/mab_synthetic_experiment_helper.py
> +            node.content['name'] = 'x'
как вариант -- добавить флаг в descriptive_id, чтобы его можно было пересчитать принудительно. ну и оставить там предупреждение о такого рода действиях
здесь так сделано из-за того, что при адаптации в имена нод ставится их `uid`

2023-06-27 12:27 UTC, maypink commented on golem/core/optimisers/adaptive/context_agents.py
> +    :param mode: mode of encoding. Available type: 'ohe' and 'label', default -- 'label'
one hot encoding

2023-06-27 12:32 UTC, maypink commented on golem/core/optimisers/adaptive/context_agents.py
> +    return encode_operations(operations=operations, available_operations=available_operations)
цель -- сделать ту же матрицу смежности, но легче. то есть граф будет кодироваться напрямую операциями нод, между которыми есть ребро. например, граф 1 --> 2 --> 3 будет закодирован так [1, 2, 2, 3]

2023-06-27 12:45 UTC, maypink commented on golem/core/optimisers/adaptive/mab_agents/contextual_mab_agent.py
> +                contexts.append(self._context_agent(ob))
бывает, когда [на предсказание приходит центр кластера](https://github.com/aimclub/GOLEM/pull/129/files#diff-b6cf9baf15bb8280215954f2c5c9321bacb8f545dc267a54f81737e75bddc17eR82)

2023-06-27 12:47 UTC, maypink commented on experiments/mab/mab_synthetic_experiment_helper.py
> +
[done](https://github.com/aimclub/GOLEM/pull/129/commits/5c8c79d3263ae8dd0365adf4a64239d22096837d#diff-b6cf9baf15bb8280215954f2c5c9321bacb8f545dc267a54f81737e75bddc17eR217)

2023-06-27 12:50 UTC, maypink commented on golem/core/optimisers/adaptive/context_agents.py
> +def operations_encoding(obs: Any, available_operations: List[str]) -> List[int]:
[done](https://github.com/aimclub/GOLEM/pull/129/commits/5c8c79d3263ae8dd0365adf4a64239d22096837d#diff-bad84581f7c5cf3b0cb8464e14e3d829f3a85a0cde01ce6ad9bf1acf7fe56d20R80)
`operations_quantity` -- функция для получения эмбеддинга графа, `encode_operations` -- сопоставляет переданным операциям вектора

2023-06-27 12:52 UTC, maypink commented
> Пробовала что-нибудь запускать с этими способами кодирования?

запускала на синтетическом примере, но скорее для проверки работоспособности, а не сравнения полученных метрик

2023-06-29 05:29 UTC, gkirgizov commented on golem/core/optimisers/adaptive/context_agents.py
> +    return encode_operations(operations=operations, available_operations=available_operations)
Может, как-то помечать (0?) окончание перечисления ребер одной ноды? Иначе у нас очень неоднозначный энкодинг получается.

2023-06-29 19:25 UTC, maypink commented on golem/core/optimisers/adaptive/context_agents.py
> +    return encode_operations(operations=operations, available_operations=available_operations)
да энкодинг-то однознозначно кодирует граф -- каждое ребро закодировано двумя последовательными числами, каждое число -- принадлежит только к одному из ребер
а с точки зрения смысла, логики, целесообразности и прочего -- может и неоднозначно, да)) но добавление 0 не вижу, как может помочь, кажется, оно излишне

2023-07-05 04:39 UTC, gkirgizov approved these changes

2023-07-05 13:23 UTC, merged