Check structural diversity
aimclub/GOLEM pull request #131
Opened 2023-06-20 12:38 UTC by maypink

WIP

2023-06-26 10:55 UTC, nicl-nno commented on golem/core/dag/graph_delegate.py
> +def reset_descriptive_id(func):
Меня конечно смущает что очень легко ошибиться при добавлении новых методов и забыть поставить декоратор. И всё начнет работать криво. Не знаю как от этого лучше подстраховаться. Как минимум, стоит расширить тест чтобы он все CRUD-методы графа тестировал на то, что desc_id изменился.

И что будет если новый перечень nodes будет передан через setter.

2023-06-26 10:57 UTC, nicl-nno commented on test/integration/test_structural_diversity.py
> +            assert ratio_unique[i] > DIVERSITY_THRESHOLD
А если появилось быстрое вычисление desc_id - то проверка не на каждом поколении вообще актуальна?

2023-06-26 10:58 UTC, nicl-nno commented on golem/core/dag/graph_delegate.py
> +def reset_descriptive_id(func):
Может есть смысл сбрасывать desc_id в момент в момент изменения nodes (в сеттере или ещё как-то)?

2023-06-26 11:38 UTC, gkirgizov commented
@YamLyubov , а можешь построить такой же график доли уникальных, как ты строила, чтобы проверить изменения?

![image](https://github.com/aimclub/GOLEM/assets/10994117/92402427-a863-4280-8779-2c4878564b40)

2023-06-26 12:31 UTC, gkirgizov requested changes

2023-06-26 12:31 UTC, gkirgizov commented on test/unit/adapter/test_adapter.py
> +    opt_graph.update_node(changed_node, new_node)
Этот пример натолкнул на такие мысли. Могут ли где-то в Федоте в процессе обучения Ноды менять своим гиперпараметры? Например, в процессе тюнинга. Тогда descriptive_id изменится в обход графа.

2023-06-26 12:48 UTC, YamLyubov commented
Сейчас пропал тренд на снижение разнообразия, но все-равно наследование будто тянет разнообразие вниз
![diversity](https://github.com/aimclub/GOLEM/assets/43475193/7e5f4853-39a3-4f18-a439-3a4452ee14cc)
![diversity_2](https://github.com/aimclub/GOLEM/assets/43475193/33fdac49-2b17-4afd-8aa4-0c6bb4a12f38)

2023-06-26 13:47 UTC, maypink commented
> Сейчас пропал тренд на снижение разнообразия, но все-равно наследование будто тянет разнообразие вниз ![diversity](https://user-images.githubusercontent.com/43475193/248796695-7e5f4853-39a3-4f18-a439-3a4452ee14cc.png) ![diversity_2](https://user-images.githubusercontent.com/43475193/248799371-33fdac49-2b17-4afd-8aa4-0c6bb4a12f38.png)

а мутации вне поля зрения теперь? или куда они там попрятались

2023-06-26 19:59 UTC, nicl-nno commented on test/unit/adapter/test_adapter.py
> +    opt_graph.update_node(changed_node, new_node)
Насколько я помню - может, например для knn N может менять если данных мало.

2023-06-27 07:20 UTC, YamLyubov commented
> а мутации вне поля зрения теперь? или куда они там попрятались
У нас цикл репродукции теперь в ReproductionController спрятан. Но могу и с этой инфой графики построить - сейчас займусь

2023-06-27 08:30 UTC, YamLyubov reviewed
Вот с большими подробностями
![diversity_single_obj](https://github.com/aimclub/GOLEM/assets/43475193/3a08cea4-c977-4f0a-b344-8f25e2a52559)
![diversity_multi_obj](https://github.com/aimclub/GOLEM/assets/43475193/6e2b641b-a664-4bed-93ba-a415f09f0e50)

2023-06-27 09:03 UTC, maypink commented on golem/core/optimisers/genetic/operators/mutation.py
> +        return individual, mutation_applied, is_applied
`mutation_applied` несет в себе информацию о последней попытке применить мутацию, а `is_applied` говорит о том, была ли хоть раз предпринята эта попытка
btw, название наверно не очень, поменяла на `application_attempt`

2023-06-27 09:26 UTC, maypink commented on golem/core/optimisers/genetic/operators/elitism.py
> +        if not_repetitive_inds:
[done](https://github.com/aimclub/GOLEM/pull/131/commits/5fdb2994b0aeb97c91c8849527e1da8385f61f46#diff-8799d4a458b6cf75a93483e0aa1542328a7c37dc008a6b5a469d7778e1814aeaR34)

2023-06-27 09:26 UTC, maypink commented on golem/core/optimisers/genetic/operators/elitism.py
> +        final_population = sorted(final_population, key=lambda individual: individual.fitness, reverse=True)
[done](https://github.com/aimclub/GOLEM/pull/131/commits/5fdb2994b0aeb97c91c8849527e1da8385f61f46#diff-8799d4a458b6cf75a93483e0aa1542328a7c37dc008a6b5a469d7778e1814aeaL39)

2023-06-27 09:27 UTC, maypink commented on test/unit/optimizers/gp_operators/test_gp_operators.py
> +        assert graphs_same(new_population[i].graph, target_new_population[i].graph)
потому что `get_structure_unique_population` ведет проверку по порядку. они там могут перемешаться, но только в случае, если их меньше, чем `MIN_POP_SIZE`, это кейс `test_recover_pop_size_after_structure_check` теста

2023-06-27 09:28 UTC, maypink commented on golem/core/optimisers/populational_optimizer.py
> +                        new_population = self.get_structure_unique_population(population=new_population)
вынесла в [константу](https://github.com/aimclub/GOLEM/pull/131/commits/5fdb2994b0aeb97c91c8849527e1da8385f61f46#diff-470f0adbc234140fd266544abfca6c8465573f627c6034ab9054442e76777f0bR47) и в [гиперпараметр](https://github.com/aimclub/GOLEM/pull/131/commits/5fdb2994b0aeb97c91c8849527e1da8385f61f46#diff-470f0adbc234140fd266544abfca6c8465573f627c6034ab9054442e76777f0bR47)

2023-06-27 09:28 UTC, maypink commented on golem/core/optimisers/populational_optimizer.py
> +from test.unit.utils import graphs_same
[done](https://github.com/aimclub/GOLEM/pull/131/commits/5fdb2994b0aeb97c91c8849527e1da8385f61f46#diff-beda83dfc5f4b2842620466bd408cba32eaceb430e9351c9d5ab853f6af0afdbL18)

2023-06-27 09:29 UTC, maypink commented on golem/core/optimisers/populational_optimizer.py
> +                unique_population.append(cur_ind)
[такой вариант](https://github.com/aimclub/GOLEM/pull/131/commits/5fdb2994b0aeb97c91c8849527e1da8385f61f46#diff-beda83dfc5f4b2842620466bd408cba32eaceb430e9351c9d5ab853f6af0afdbR154)

2023-06-27 09:30 UTC, maypink commented on golem/core/optimisers/populational_optimizer.py
> +        return unique_population
[done](https://github.com/aimclub/GOLEM/pull/131/commits/5fdb2994b0aeb97c91c8849527e1da8385f61f46#diff-beda83dfc5f4b2842620466bd408cba32eaceb430e9351c9d5ab853f6af0afdbR124)

2023-06-28 05:46 UTC, gkirgizov commented on test/integration/test_structural_diversity.py
> +        if i % STRUCTURAL_DIVERSITY_FREQUENCY_CHECK == 0:
Может, все-таки вынести ее в параметры алгоритма? Звучит как штука, которую иногда может захотеться отключить. Как минимум для сравнения

2023-06-28 05:46 UTC, gkirgizov commented on test/integration/test_structural_diversity.py
> +        if i % 5 == 0:
Может, все-таки вынести ее в параметры алгоритма? Звучит как штука, которую иногда может захотеться отключить. Как минимум для сравнения вместе\без

2023-06-28 05:49 UTC, gkirgizov commented on golem/core/optimisers/genetic/operators/mutation.py
> +        return individual, mutation_applied, is_applied
Так у нас `mutation_applied` будет None если попытка не была предпринята ни разу, и not None, если хоть раз была.

2023-06-28 11:37 UTC, maypink commented on golem/core/optimisers/genetic/operators/mutation.py
> +        return individual, mutation_applied, is_applied
ну нет, `mutation_applied` на каждой итерации может устанавливаться как в `None`, так и в не `None` в зависимости от того, что вернет `_apply_mutations`. может случиться так, что на последней итерации цикла `mutation_applied` установится в None, хотя до этого мутации были применены, но графы получались некорректные

2023-06-28 21:39 UTC, maypink commented on test/integration/test_structural_diversity.py
> +        if i % STRUCTURAL_DIVERSITY_FREQUENCY_CHECK == 0:
[done](https://github.com/aimclub/GOLEM/pull/131/commits/bcf9cd4ef5068bec4deebd74fef19a5a590b657f#diff-19cbb7d4bad2d48ec4640167c39b7cb7e562a80710ace2a8b459d931bed6d35fR49)

2023-06-28 21:43 UTC, maypink commented on golem/core/dag/graph_delegate.py
> +def reset_descriptive_id(func):
[покрыла тестами](https://github.com/aimclub/GOLEM/pull/131/commits/57fa2d2424f2830b0eb401bfe47bc20d7d1b9d4a#diff-9b57e32e19c9dbcc26efc77d3d0ac3cfcb568482c76ae2ba886cb4a028b569ddR321) и через setter тоже [сбрасывается](https://github.com/aimclub/GOLEM/pull/131/commits/bd5e069f8f1608f1be56330f52bbf4e649043846#diff-b70ed739f3e981df9261f1b4769fa93fd4d0032f661f8eb8c99e7b45ecf2019eR174)

2023-06-28 21:54 UTC, maypink commented on golem/core/dag/graph_delegate.py
> +        self._descriptive_id = None
[переселила](https://github.com/aimclub/GOLEM/pull/131/commits/bd5e069f8f1608f1be56330f52bbf4e649043846#diff-b70ed739f3e981df9261f1b4769fa93fd4d0032f661f8eb8c99e7b45ecf2019eR16)

2023-06-29 05:23 UTC, gkirgizov requested changes
Имею следующие мысли насчет descriptive_id:
- Можно сделать так: `graph.nodes[0].content['something'] = "evil_change"` и обойти кэширование id. Как в одном из комментов ответил Коля, Федот такое использует.
- Ни предупредить программиста в виде warning-а, ни как-то запретить это сейчас нельзя. Следить за этим вне кода (рассказать всем как правильно теперь изменять узлы) -- невозможно.
- Я вижу два решения. Первое -- отказаться от кэширования) Второе -- позволить узлам LinkedGraph сообщать об изменениях в себе. Можем подробнее это обсудить отдельно.
- Такие значимые изменения лучше делать отдельными PR, тк теперь эта функциональность задерживает основные изменения PR. Плюс, будет невозможно атомарно откатить именно эти изменения, а есть шанс, что это может понадобиться. Поэтому, пожалуйста, выдели их в отдельный PR.
- Любые оптимизации должны быть подтверждены числами. Нужно запустить профайлер без и вместе с кэшированием, и посмотреть, сколько времени занимает это вычисление `descriptive_id` и сколько раз вызывается.

Вообще, задача кэширования композитных структур является сложной задачей именно по этой причине. В каком-то виде информацию об изменениях приходится прокидывать во все элементы структуры. и обратно, от элементов структуры (узлов графа, например) к композитам (графу). С наскоку парой изменений где-то "сверху" их обычно не получается решить, по опыту. Почти всегда приходится лезть глубже.

2023-06-29 05:23 UTC, gkirgizov commented on golem/core/dag/linked_graph.py
> +        self._descriptive_id = None
Почему здесь не через декоратор?

2023-06-29 07:28 UTC, nicl-nno commented
>Можно сделать так: graph.nodes[0].content['something'] = "evil_change" и обойти кэширование id

Так а если nodes обернуть в setter и в нем сбрасывать закэшированный - это не решит проблему?

2023-06-29 10:50 UTC, maypink commented on golem/core/optimisers/optimizer.py
> +    gen_structural_check: int = STRUCTURAL_DIVERSITY_FREQUENCY_CHECK
`structural_diversity_frequency_check` вроде норм, само поле так же [переименовала](https://github.com/aimclub/GOLEM/pull/131/commits/360a7bc15e9d92e2619791e4bb10847dd171e1a7#diff-470f0adbc234140fd266544abfca6c8465573f627c6034ab9054442e76777f0bR47)

2023-06-29 10:52 UTC, maypink commented on golem/core/optimisers/populational_optimizer.py
> +        unique_population_with_ids = dict(zip(descriptive_ids, population))
[done](https://github.com/aimclub/GOLEM/pull/131/commits/43fc06d107ad6bbfdf82289aa8a44189e7105641#diff-beda83dfc5f4b2842620466bd408cba32eaceb430e9351c9d5ab853f6af0afdbR154)

2023-06-29 10:53 UTC, maypink commented on golem/core/dag/linked_graph.py
> +        self._descriptive_id = None
убрала все с связанное с кешированием descriptive_id

2023-06-29 12:29 UTC, nicl-nno approved these changes

2023-07-05 04:12 UTC, gkirgizov commented
> > Можно сделать так: graph.nodes[0].content['something'] = "evil_change" и обойти кэширование id
> 
> Так а если nodes обернуть в setter и в нем сбрасывать закэшированный - это не решит проблему?

Мы можем просто через getter изменить любую ноду. Так что за этим простыми средствами  не обойтись

2023-07-05 04:14 UTC, gkirgizov approved these changes

2023-07-05 13:32 UTC, merged