Fix recursions for cycled graphs
aimclub/GOLEM pull request #137
Opened 2023-06-29 08:58 UTC by YamLyubov

WIP

2023-07-05 04:38 UTC, gkirgizov requested changes

2023-07-05 04:38 UTC, gkirgizov commented on golem/core/dag/graph.py
> +            return sorted(self.nodes, key=lambda x: str(x.uid))[0].descriptive_id
Зачем тут сортировать? Вызов desiptive_id это обход графа. Нужно обойтись без него, если это не является строго необходимым

2023-07-05 04:38 UTC, gkirgizov commented on golem/core/dag/graph_utils.py
>      return height
Перепиши рекурсивный обход через цикл, пожалуйста. В Питоне рекурсия дорого обходиться, уж тем более для больших графов.

2023-07-05 04:38 UTC, gkirgizov commented on golem/core/dag/graph_utils.py
> +    return node_depth(node) - 1 if node_depth(node) > 0 else -1
здесь эта функция будет дважды вычисляться

2023-07-05 04:38 UTC, gkirgizov commented on golem/core/dag/graph_utils.py
> +        parent_depths = [node_depth(next_node, copy(visited_nodes)) for next_node in node.nodes_from]
Перепиши без рекурсии

2023-07-05 04:38 UTC, gkirgizov commented on golem/core/dag/graph_utils.py
> +    return len(list(simple_cycles(nx_graph))) > 0
Давай обойдемся без зависимостей от networkx. И для того, чтобы найти хоть один цикл, не нужно перечислятьт все возможные циклы. Очень неэффективно

2023-07-05 04:38 UTC, gkirgizov commented on golem/core/optimisers/genetic/operators/base_mutations.py
> +        graph_cycled = distance_to_primary_level(node) < 0
можно чуть корое записать через `or`

2023-07-05 04:38 UTC, gkirgizov commented on golem/core/optimisers/genetic/operators/base_mutations.py
> +    root_node = choice(ensure_wrapped_in_sequence(graph.root_node)) if graph.root_node else None
Разве `graph.root_nodes()` уже не возвращает sequence?

2023-07-05 04:38 UTC, gkirgizov commented on golem/core/optimisers/genetic/operators/base_mutations.py
> +                                     [n.descriptive_id for n in ordered_subnodes_hierarchy(source_node)])
Может, вынести это во вспомогательную функцию?

2023-07-05 04:38 UTC, gkirgizov commented on golem/core/optimisers/genetic/operators/base_mutations.py
> +                break
А в чем смысл этого условия здесь? Не улавливаю

2023-07-05 04:38 UTC, gkirgizov commented on golem/core/optimisers/genetic/operators/base_mutations.py
> +                break
Ниже как будто наоборот пытаемся избежать добавления цикла. А тут, выходит, уже не заботимся о циклах?

2023-07-06 08:22 UTC, YamLyubov commented on golem/core/dag/graph.py
> +            return sorted(self.nodes, key=lambda x: str(x.uid))[0].descriptive_id
Добавила соритировку для случая, когда мы имеем два графа с одинаковой структурой, но без корневых узлов. Для таких графов сортировка может помочь получить одинаковые descriptive_id

2023-07-10 12:55 UTC, YamLyubov commented on golem/core/dag/graph_utils.py
>      return height
[Done ](https://github.com/aimclub/GOLEM/pull/137/files?diff=unified&w=0#diff-a9919eed5feb46613e14614e46806a5c5a5e79ee3393acf7312cbd4d53aa104fR19-R27)

2023-07-10 12:56 UTC, YamLyubov commented on golem/core/dag/graph_utils.py
> +    return node_depth(node) - 1 if node_depth(node) > 0 else -1
[Done](https://github.com/aimclub/GOLEM/pull/137/files?diff=unified&w=0#diff-a9919eed5feb46613e14614e46806a5c5a5e79ee3393acf7312cbd4d53aa104fR36-R37)

2023-07-10 12:56 UTC, YamLyubov commented on golem/core/dag/graph_utils.py
> +        parent_depths = [node_depth(next_node, copy(visited_nodes)) for next_node in node.nodes_from]
[Done ](https://github.com/aimclub/GOLEM/pull/137/files?diff=unified&w=0#diff-a9919eed5feb46613e14614e46806a5c5a5e79ee3393acf7312cbd4d53aa104fR104-R118)

2023-07-10 12:56 UTC, YamLyubov commented on golem/core/dag/graph_utils.py
> +    return len(list(simple_cycles(nx_graph))) > 0
[Done](https://github.com/aimclub/GOLEM/pull/137/files?diff=unified&w=0#diff-a9919eed5feb46613e14614e46806a5c5a5e79ee3393acf7312cbd4d53aa104fR158)

2023-07-10 12:58 UTC, YamLyubov commented on golem/core/optimisers/genetic/operators/base_mutations.py
> +        graph_cycled = distance_to_primary_level(node) < 0
Тут через or не получится написать. Это and, но мы не может вычислить  `distance_to_primary_level(node)`, если `node=None`

2023-07-10 12:59 UTC, YamLyubov commented on golem/core/optimisers/genetic/operators/base_mutations.py
> +    root_node = choice(ensure_wrapped_in_sequence(graph.root_node)) if graph.root_node else None
[Заменила](https://github.com/aimclub/GOLEM/pull/137/files?diff=unified&w=0#diff-22597fa80790447c12350557295b46256d87b8a700fcc1b6c0331f6b49765141R89)

2023-07-10 13:00 UTC, YamLyubov commented on golem/core/optimisers/genetic/operators/base_mutations.py
> +                break
Да, я решила, что если граф уже имеет циклы, значит мы можем добавить и новые.

2023-07-10 13:49 UTC, gkirgizov requested changes

2023-07-10 13:49 UTC, gkirgizov commented on golem/core/dag/linked_graph.py
> +            return max(map(node_depth, self.root_nodes()))
Если разрешить в node_depth передавать несколько нод, то можно обойтись одним вызовом функции

2023-07-10 13:53 UTC, YamLyubov commented on golem/core/dag/graph.py
> +            return sorted(self.nodes, key=lambda x: str(x.uid))[0].descriptive_id
Про копию понимаю - идея в том, чтобы каким-то образом выбрать одинаковые ноды в этих двух графах. В данном случае выбираем первую ноду по uid.
str(uid) нужет, так как в некоторых случаях у нас uid не строка, а int

2023-07-10 14:46 UTC, YamLyubov commented on golem/core/dag/linked_graph.py
> +            return max(map(node_depth, self.root_nodes()))
[Done](https://github.com/aimclub/GOLEM/pull/137/files#diff-a9919eed5feb46613e14614e46806a5c5a5e79ee3393acf7312cbd4d53aa104fR97)

2023-07-11 06:33 UTC, gkirgizov commented on golem/core/dag/linked_graph.py
> +            return max(map(node_depth, self.root_nodes()))
Ты просто скрыла N вызовов функции. Я имел ввиду, здесь можно обойти граф для глубины 1 раз, а не N

2023-07-11 06:35 UTC, gkirgizov commented on golem/core/dag/graph.py
> +            return sorted(self.nodes, key=lambda x: str(x.uid))[0].descriptive_id
Понял идею с копией.
А почему нас сортировка int-ов не устраивает?

2023-07-11 06:41 UTC, gkirgizov requested changes

2023-07-11 06:41 UTC, gkirgizov commented on golem/core/optimisers/genetic/operators/base_mutations.py
> +                [n.descriptive_id for n in ordered_subnodes_hierarchy(source_node)])
Это можно переписать через dfs за один проход? 
А то здесь логика сложновата, может не для всех графов быть определена (`ordered_subnodes_hierarchy`)  и плюс каждый вызов desciptive_id будет обходить часть графа.

2023-07-13 09:02 UTC, gkirgizov commented on golem/core/dag/graph.py
> +            return sorted(self.nodes, key=lambda x: str(x.uid))[0].descriptive_id
Ах, вон что. Понял, будем знать. Пофикси тут в BaseNetworkxAdapter , пожалуйста

2023-07-14 13:26 UTC, YamLyubov commented on golem/core/dag/linked_graph.py
> +            return max(map(node_depth, self.root_nodes()))
Через [рекурсию сделала](https://github.com/aimclub/GOLEM/pull/137/files#diff-a9919eed5feb46613e14614e46806a5c5a5e79ee3393acf7312cbd4d53aa104fR97), чтобы минимальное количество обходив было. Не могу понять как это через рекурсию переписать

2023-07-14 13:29 UTC, YamLyubov commented on golem/core/optimisers/genetic/operators/base_mutations.py
> +                [n.descriptive_id for n in ordered_subnodes_hierarchy(source_node)])
Не через dfs, но по-моему[ так проще](https://github.com/aimclub/GOLEM/pull/137/files#diff-22597fa80790447c12350557295b46256d87b8a700fcc1b6c0331f6b49765141R112)

2023-07-14 13:31 UTC, YamLyubov commented on golem/core/dag/graph.py
> +            return sorted(self.nodes, key=lambda x: str(x.uid))[0].descriptive_id
По большей части исправления для [адаптера молекул ](https://github.com/aimclub/GOLEM/pull/137/files#diff-f4f191c9f4613b327a578fe5857e47c49a9a0a61d3a13c2483789e0131ed5460R28)понадибились

2023-07-17 05:59 UTC, gkirgizov commented on golem/core/dag/linked_graph.py
> +            return max(map(node_depth, self.root_nodes()))
Не нужно через рекурсию) Все было правильно. У тебя алгоритм стартовал с 1 узла. Он добавлялся в список parents (кажется). Потом алгоритм работает пока список не пуст. Так вот можно вместо 1 исходного узла передавать несколько узлов, добавлять их в parents, и начинать обход с них.

2023-07-17 06:00 UTC, gkirgizov requested changes
См. коммент про node_depth

2023-07-17 12:34 UTC, YamLyubov commented on golem/core/dag/linked_graph.py
> +            return max(map(node_depth, self.root_nodes()))
Теперь поняла) [Сделала](https://github.com/aimclub/GOLEM/pull/137/files#diff-a9919eed5feb46613e14614e46806a5c5a5e79ee3393acf7312cbd4d53aa104fR106)

2023-07-18 09:16 UTC, gkirgizov approved these changes

2023-07-18 09:50 UTC, merged