Warm-start bandit models
aimclub/GOLEM pull request #138
Opened 2023-06-29 18:33 UTC by gkirgizov

Provides infrastructure for collecting histories and training models separately from optimization.
Provides experiment code.
Introduces new interface method in `GraphOptimizer` for warm starting internally used models.

Closes #81

2023-08-24 04:34 UTC, gkirgizov commented
@YamLyubov , please check commit `[Fix error with content loading of molecules](https://github.com/aimclub/GOLEM/pull/138/commits/d9399bf961cc7a06c849d8e9b9a65e8055c7c1fe)` in particular

2023-08-28 08:43 UTC, maypink requested changes

2023-08-28 08:43 UTC, maypink commented on golem/core/optimisers/adaptive/agent_trainer.py
> +    def fit(self, histories: Iterable[OptHistory], validate_each: int = -1) -> OperatorAgent:
было бы славно заиметь и здесь докстрингу на тему того, что validate_each -- разбиение каждой X истории для  валидации

2023-08-28 08:43 UTC, maypink commented on golem/core/optimisers/adaptive/history_collector.py
> +            optimizer.history.save(self.save_path / history_filename)
и хочется пример использования во всяком случае. а то непонятно, почему `HistoryCollector` runs Optimizer to collect histories, я бы ожидала, что класс будет собирать опыт из указанной директории, как это делает `HistoryReader`

2023-08-28 08:49 UTC, maypink requested changes

2023-08-28 08:49 UTC, maypink commented on golem/core/optimisers/adaptive/experience_buffer.py
> +        action = result.parent_operator.operators[0]
бтв когда я писала подобную штуку для MetaFEDOT, столкнулась с тем, что мутации нужно хранить в ExperienceBuffer как объекты, а не как строки. При подгрузке из историй вроде бы получаются именно строки, с этим не возникает проблем?

2023-10-13 10:01 UTC, pep8speaks commented
Hello @gkirgizov! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`examples/molecule_search/experiment.py`](https://github.com/aimclub/GOLEM/blob/2e3b70627015f32c2ebb54ced184a2d75f74f540/examples/molecule_search/experiment.py):

> [Line 20:1](https://github.com/aimclub/GOLEM/blob/2e3b70627015f32c2ebb54ced184a2d75f74f540/examples/molecule_search/experiment.py#L20): [F401](https://duckduckgo.com/?q=pep8%20F401) 'golem.core.optimisers.adaptive.history_collector.HistoryCollector' imported but unused

2023-10-23 14:17 UTC, maypink commented on examples/molecule_search/experiment.py
> -                   adaptive_kind=MutationAgentTypeEnum.random,
поменяла LearningPolicy у бандита, теперь все ок

2023-10-24 09:55 UTC, YamLyubov approved these changes

2023-10-25 14:01 UTC, maypink approved these changes

2023-10-25 14:19 UTC, merged