Add integration test and runner
aimclub/GOLEM pull request #14
Opened 2022-12-20 17:33 UTC by gkirgizov

2022-12-20 17:40 UTC, gkirgizov commented
Requires fix for #7

2022-12-27 10:09 UTC, YamLyubov requested changes

2022-12-27 10:09 UTC, YamLyubov commented on test/integration/test_quality_improvement.py
> +    complexity_improved = pareto_front_metrics[-1] < first_pop_metrics[1]
Здесь ```first_pop_metrics[1]``` скорее всего имелось в виду ```first_pop_metrics[-1]```

2022-12-27 10:09 UTC, YamLyubov commented on test/integration/test_quality_improvement.py
> +from golem.core.optimisers.random.random_search import RandomSearchOptimizer
Импорты не используются

2022-12-27 10:09 UTC, YamLyubov commented on .github/workflows/manual-build.yml
> +        python-version: [ 3.7, 3.8, 3.9 ]
Наверное стоит в unit-built.yml тоже добавить 3.9

2022-12-27 13:01 UTC, nicl-nno commented on .github/workflows/manual-build.yml
> +        python-version: [ 3.7, 3.8, 3.9 ]
Тогда и 3.7 можно убрать - кажется в 2023 его поддержка заканчивается.

2023-01-12 14:59 UTC, gkirgizov commented on test/integration/test_quality_improvement.py
> +    complexity_improved = pareto_front_metrics[-1] < first_pop_metrics[1]
для двух значений они совпадают. но поправлю. а ты можешь воспроизвести? у меня не падает

2023-01-12 14:59 UTC, gkirgizov commented on test/integration/test_quality_improvement.py
> +from golem.core.optimisers.random.random_search import RandomSearchOptimizer
поправил

2023-01-14 14:40 UTC, gkirgizov commented on test/integration/test_quality_improvement.py
> +    complexity_improved = pareto_front_metrics[-1] < first_pop_metrics[1]
я пока залью, для отчетности. если смодешь воспроизвести -- поправлю

2023-01-14 14:40 UTC, merged