add RewardAgent
aimclub/GOLEM pull request #148
Opened 2023-07-18 14:39 UTC by maypink

WIP

2023-08-07 14:43 UTC, maypink commented
Получается так
Здесь сравниваются разные размеры окна (1, 3, 5) //на картинках подписи должны быть соответственно `bandit_base`, `bandit_3_1.0`, `bandit_5_1.0`, забыла переименовать
![image](https://github.com/aimclub/GOLEM/assets/57305249/8813cec1-684d-422d-9cb3-99ee320536a5)
![image](https://github.com/aimclub/GOLEM/assets/57305249/464e17fd-0d4a-4932-9c51-70e4b9528028)

А здесь сравниваются разные dacaying факторы (0.6, 0.8, 1):
![image](https://github.com/aimclub/GOLEM/assets/57305249/afedc42b-0dc3-4cae-9c9d-8088e5125279)
![image](https://github.com/aimclub/GOLEM/assets/57305249/6473da36-1589-4806-bc29-5df074decc6c)

2023-08-10 07:34 UTC, gkirgizov commented
Касательно графиков Metrics -- подскажи, что именно за значения изображены? Метрики в конце оптимизации?

2023-08-10 09:04 UTC, gkirgizov requested changes

2023-08-10 09:04 UTC, gkirgizov commented on examples/adaptive_optimizer/mab_experiment_different_targets.py
> +                        decaying_factor: float = 1.0, window_size: int = 5):
В статье под размером окна тоже имеется ввиду количество поколений? Или количество применений для каждого действия?

2023-08-10 10:22 UTC, maypink commented on examples/adaptive_optimizer/mab_experiment_different_targets.py
> +                        decaying_factor: float = 1.0, window_size: int = 5):
в статье именно кол-во применений оператора. в нашей постановке задачи показалось странным измерять окно количеством применений оператора, а не количество поколений, так как в големе дообучение агента происходит после каждого поколения, а не онлайн
можно попробовать оперировать кол-вом операторов, но кажется тогда информация в агенте будет не up to date
![image](https://github.com/aimclub/GOLEM/assets/57305249/402fe443-40e7-4b51-99c5-e944876106af)

2023-08-10 10:27 UTC, maypink commented on golem/core/optimisers/adaptive/mab_agents/mab_agent.py
> +        self._reward_agent = RewardAgent(decaying_factor=decaying_factor)
[done](https://github.com/aimclub/GOLEM/pull/148/commits/777239bf8b053382a3aafd6f211790e73d8fa4a7#diff-c95bcd8a54bd67d1b51ef99b699b5384c11e915c0d34cc6eaa0e95a7bc2f0909R6)

2023-08-10 10:27 UTC, maypink commented on golem/core/optimisers/adaptive/reward_agent.py
> +    def get_decay_values_for_arms(self, rewards: List[ObsType], arms: List[int]) -> Tuple[List[int], List[float]]:
[done](https://github.com/aimclub/GOLEM/pull/148/commits/777239bf8b053382a3aafd6f211790e73d8fa4a7#diff-c95bcd8a54bd67d1b51ef99b699b5384c11e915c0d34cc6eaa0e95a7bc2f0909R16)

2023-08-10 10:28 UTC, maypink commented on experiments/mab/experiment_with_fickle_mutations/mab_experiment_with_fickle_mutations.py
> +    return initial_opt_graphs
[done](https://github.com/aimclub/GOLEM/pull/148/commits/b0639a9bc9ab2e6eeaee2e1c0e22eeb490b9e155#diff-bffbce5903bc74f55b0379e082ca0503a8451473ab5c2a95ecc87674ae7144d2R51)

2023-08-10 10:28 UTC, maypink commented on golem/core/optimisers/genetic/gp_params.py
> +    :param window_size: the size of sliding window for Multi-Armed Bandits to decrease variance.
[done](https://github.com/aimclub/GOLEM/pull/148/commits/b0639a9bc9ab2e6eeaee2e1c0e22eeb490b9e155#diff-73bb960de1a0bcefcaefd1a248dc834ec7bef173d58e560c508d17da95aa2f08R72)

2023-08-10 10:28 UTC, maypink commented
> Касательно графиков Metrics -- подскажи, что именно за значения изображены? Метрики в конце оптимизации?

ага, метрика в конце оптимизации

2023-08-11 08:17 UTC, gkirgizov commented
> > Касательно графиков Metrics -- подскажи, что именно за значения изображены? Метрики в конце оптимизации?
> 
> ага, метрика в конце оптимизации

Почему количество поколений отличается на графиках?

2023-08-11 08:24 UTC, gkirgizov commented
> Now, at the border of two mutations, the bandit applies such mutations to individuals that individuals which have already met before are obtained. For example, after graph reaches the size of 80 nodes, fake_add_mutation tries to decrease the graph size by 1 node, and fake_add_mutation2 tries to increase it by 2 nodes. Therefore, after [this line](https://github.com/aimclub/GOLEM/pull/148/commits/7d7d9322e8aa8a2b10f53170d84c2e51b94853ac#diff-826b69838a90fd12b907963e850a715b0af99484452f4430ef5d9913151e31c2L83), the population size is very much reduced. Now it is temporarily commented, but it seems that this is not the only setup in which such a problem will occur

Эти строчки позволяют избегать дубликатов. Если эти строчки убрать, то новое поколение будет содержать дубликаты предыдущего. Нам, кажется, это особо не нужно. Чем нам может помочь комментирование этих строчек?

Кроме того, кажется, тут должен подключиться ReproductionController, который попробует еще раз применить мутации и сгенерить новых индивидов.

2023-08-11 09:37 UTC, maypink commented
> > > Касательно графиков Metrics -- подскажи, что именно за значения изображены? Метрики в конце оптимизации?
> > 
> > 
> > ага, метрика в конце оптимизации
> 
> Почему количество поколений отличается на графиках?


потому что ограничение задается таймаутом, а не количеством поколений. полагаю, бандиты с окнами 3 и 5 предсказывают дольше ввиду большего количества данных, вот их и обгоняет базовый бандит.

2023-08-11 09:42 UTC, maypink commented
> > Now, at the border of two mutations, the bandit applies such mutations to individuals that individuals which have already met before are obtained. For example, after graph reaches the size of 80 nodes, fake_add_mutation tries to decrease the graph size by 1 node, and fake_add_mutation2 tries to increase it by 2 nodes. Therefore, after [this line](https://github.com/aimclub/GOLEM/pull/148/commits/7d7d9322e8aa8a2b10f53170d84c2e51b94853ac#diff-826b69838a90fd12b907963e850a715b0af99484452f4430ef5d9913151e31c2L83), the population size is very much reduced. Now it is temporarily commented, but it seems that this is not the only setup in which such a problem will occur
> 
> Эти строчки позволяют избегать дубликатов. Если эти строчки убрать, то новое поколение будет содержать дубликаты предыдущего. Нам, кажется, это особо не нужно. Чем нам может помочь комментирование этих строчек?
> 
> Кроме того, кажется, тут должен подключиться ReproductionController, который попробует еще раз применить мутации и сгенерить новых индивидов.

да, он должен подключаться и подключается. но на границе двух мутаций бандиту нужно время, чтобы понять, что мутацию надо изменить на другую. а в ходе применения `ReproductionController` он не успевает этого сделать и в итоге эволюционный процесс затухает ввиду недостатка уникальных индивидов.

понятно, что комментирование -- временное решение и нужно скорее давать ему больше попыток на то, чтобы выкарабкаться. просто здесь постановка самого эксперимента такая, что свитч ревордов происходит очень резко, поэтому 5 попыток -- мало

2023-08-14 08:02 UTC, gkirgizov commented
> понятно, что комментирование -- временное решение и нужно скорее давать ему больше попыток на то, чтобы выкарабкаться. просто здесь постановка самого эксперимента такая, что свитч ревордов происходит очень резко, поэтому 5 попыток -- мало

Может, увеличить колчество попыток?
Есть ли другие мысли о том, как это в будущем можно пофиксить?

Мне кажется, что проблема довольно специфичного синтетического примера может быть не очень актуальна для реальных запусков. И кажется, отключение этой функциональности увеличит количество дубликатов. Хотя такое "кажется" надо подкреплять экспериментами с/без функциональности. Понять, помогает ли реально. В будущем надо нам это сделать.

2023-09-07 12:34 UTC, maypink commented
Мне кажется, что сейчас тогда разумно поступить так: оставить по дефолту так, как было, но функциональность влить. Протестировать можно будет на ближайших экспериментах, если останется время. Количество попыток пока трогать не буду, так как действительно может проблема в этом примере конкретном.

2023-09-08 14:46 UTC, YamLyubov commented on golem/core/optimisers/adaptive/operator_agent.py
> +        self._observations.append(self._current_observations)
Мы получается тут список как элемент списка добавляем?

2023-09-08 14:46 UTC, YamLyubov commented on experiments/mab/experiment_with_fickle_mutations/fickle_mutations.py
> +def fake_add_mutation(graph: OptGraph,
Насколько поняла, у трех мутаций код одинаковый, отличаются только nodes_to_add_num. Может их в одну функцию объединить, просто параметризовать?

2023-09-08 14:48 UTC, maypink commented on golem/core/optimisers/adaptive/operator_agent.py
> +        self._observations.append(self._current_observations)
[поменяла на плюс](https://github.com/aimclub/GOLEM/pull/148/commits/326775944459fe41d4f3b6a4c9be0e591124a049#diff-4c212af499045fdaf2dbca500350c788a3bca72b953ed73360a2b5c0076a9dbdR58)

2023-09-11 14:54 UTC, YamLyubov approved these changes

2023-09-13 09:46 UTC, gkirgizov approved these changes

2023-09-13 10:12 UTC, merged