Add molecule encodings for contextual bandit
aimclub/GOLEM pull request #179
Opened 2023-08-28 14:28 UTC by YamLyubov

#176

2023-09-04 12:18 UTC, maypink requested changes

2023-09-05 12:36 UTC, YamLyubov commented on examples/molecule_search/mol_encoders.py
> +    def __call__(self, obs):
[Done](https://github.com/aimclub/GOLEM/pull/179/files#diff-71802992c43fe0e311d87484347702e172dc9cc2dc06708e00aad6de2eecfa5bR130)

2023-09-05 12:39 UTC, YamLyubov commented on examples/molecule_search/mol_encoders.py
> +        if len(embedding) < 300:
Это было нужно, так как если модели не было известно слово, она возвращала 0. Сейчас сделала иначе - [неизвестные слова модель будет обрабатывать как "UNK"](https://github.com/aimclub/GOLEM/pull/179/files#diff-71802992c43fe0e311d87484347702e172dc9cc2dc06708e00aad6de2eecfa5bR132)

2023-09-05 12:39 UTC, YamLyubov commented on examples/molecule_search/mol_encoders.py
> +        model = Transformer(ALPHABET_SIZE, embedding_size, num_layers).eval()
[Done](https://github.com/aimclub/GOLEM/pull/179/files#diff-71802992c43fe0e311d87484347702e172dc9cc2dc06708e00aad6de2eecfa5bR189)

2023-09-05 12:40 UTC, YamLyubov commented on examples/molecule_search/mol_transformer/transformer.py
> +        # print("DECODER")
[Done](https://github.com/aimclub/GOLEM/pull/179/files#diff-cea8159037dc9fa211095d850573df5148e5adf89a8fa05ba274c859711e8bdcR120-R123)

2023-09-05 12:40 UTC, YamLyubov commented on test/unit/adaptive/test_context_agents.py
> +    assert np.all(encoding == result_encoding)
Done

2023-09-05 14:42 UTC, maypink approved these changes

2023-09-05 15:49 UTC, merged