Universal ExperimentAnalyzer
aimclub/GOLEM pull request #181
Opened 2023-08-30 08:44 UTC by maypink

Universal `ExperimentAnalyzer`
All main features are described below

2023-08-31 09:49 UTC, nicl-nno commented
Было бы здорово интегрировать возможность расчета стат. тестов для сравнения N историй оптимизации по разным критериям.

2023-08-31 09:49 UTC, nicl-nno commented
Было бы здорово интегрировать возможность расчета стат. тестов для сравнения N историй оптимизации по разным критериям.

2023-09-01 08:37 UTC, maypink commented
добавила поддержку стат тестов. сейчас, мне кажется, это дело будет удобно использовать, когда у нас есть две выборки на сравнение и несколько тестов, на которые хочется проверить. в таком случае результат будет в следующем формате: два файла (или сколько угодно, в зависимости от заданного формата. но по классике один для `pvalue`, второй для `statistic` значений), каждый в таком формате
![image](https://github.com/aimclub/GOLEM/assets/57305249/be14960c-aa54-4a08-9eb5-0b7987f5efa2)

2023-09-01 09:09 UTC, maypink commented
**Структурная сложность**
Структура сохранения следующая:
setup
         \
           dataset
                        \
                          здесь картинки
Удобно на это смотреть так, чтобы как минимум на глаз прикинуть стали ли решения принципиально другими
![image](https://github.com/aimclub/GOLEM/assets/57305249/d3cc8495-104b-491b-b811-8d5734226995)

2023-09-01 09:14 UTC, maypink commented
**Сохранение таблиц с метриками**

С помощью `analyze_convergence` и `analyze_metrics` можно сгенерировать таблицы с метриками.
Либо записать туда все значения, либо средние (если поставить `is_mean` в `True`). 
Оба метода возвращают словари со всеми собранными значениями в указанном формате, так что дальше их можно передавать на статистическое тестирование

Формат таблиц такой:
![image](https://github.com/aimclub/GOLEM/assets/57305249/e007600b-5b9b-48b4-9180-c818d925598d)

2023-09-01 09:56 UTC, maypink commented
**График сходимости**

С помощью `plot_convergence` можно рисовать графики сходимости с confidence interval и без
![cnae-9_convergence](https://github.com/aimclub/GOLEM/assets/57305249/0dc3442b-30e4-4218-a5be-86ec7d89f6c1)

2023-09-01 10:44 UTC, nicl-nno commented
Хорошо бы приложить скрипт с примером запуска. Можно пару тестовых историй для сравнения.

На картинках можно ещё приписать числом лучший фитнес. И указать в шапке, что это best in population.

2023-09-01 10:45 UTC, nicl-nno commented
В идеале бы иметь возможность рисовать такие же графики не по фитнесу, а по отложенной выборке - но кажется это к GOLEM-у не особо применимо.  Мб возможность кастомную метрику выводить.

2023-09-04 09:53 UTC, maypink commented
> Хорошо бы приложить скрипт с примером запуска. Можно пару тестовых историй для сравнения.
> 
> На картинках можно ещё приписать числом лучший фитнес. И указать в шапке, что это best in population.

пробросила заголовок, там еще [пр в федоте](https://github.com/aimclub/FEDOT/pull/1162) для этого 
![image](https://github.com/aimclub/GOLEM/assets/57305249/e794781a-d922-4cd7-89e0-ad8d42a83dcc).

2023-09-06 09:33 UTC, YamLyubov requested changes

2023-09-06 09:33 UTC, YamLyubov commented on experiments/experiment_analyzer.py
> +            result_dict[setup][dataset] = []
здесь тоже можно `setdefault` воспользоваться

2023-09-06 09:33 UTC, YamLyubov commented on experiments/experiment_analyzer.py
> +                    dict_with_metrics[metric] = dict()
Можно заменить на `dict_with_metrics.set_default(metric, dict())`

2023-09-06 09:33 UTC, YamLyubov commented on experiments/experiment_analyzer.py
> +        """ Method to analyze specified metrics.
Не хватает описания, какую структуру должен иметь анализируемый файл

2023-09-06 09:33 UTC, YamLyubov commented on experiments/experiment_analyzer.py
> +                    continue
Похожий код несколько раз встречается, может можно его как-то в одном месте задать?

2023-09-06 09:33 UTC, YamLyubov commented on experiments/experiment_analyzer.py
> +        :param data_to_analyze: data to analyze. NB! data must have the specified format
Не совсем понятно, какой именно должен быть формат данных. Что именно должны эти словари содержать?

2023-09-06 09:33 UTC, YamLyubov commented on experiments/experiment_analyzer.py
> +        :param stat_tests: list of functions of statistical tests to perform.
Сюда бы еще пример функций)

2023-09-06 11:17 UTC, nicl-nno approved these changes

2023-09-06 11:18 UTC, nicl-nno commented
Ещё можно пример данных в zip или tar.gz закатать и распаковывать уже на месте.

2023-09-06 13:08 UTC, maypink commented on experiments/experiment_analyzer.py
> +                    continue
[done](https://github.com/aimclub/GOLEM/pull/181/commits/d66e4a9aa2141d6974e835d6943e9c577781b7a8#diff-ea7cc5126ecede10ac12864ef00f36114d7f0fd9231fb4171f9cebf199042bfeR312)

2023-09-06 13:09 UTC, maypink commented on experiments/experiment_analyzer.py
> +        """ Method to analyze specified metrics.
а там речь про сам тип шла, [указала его еще раз в докстринге](https://github.com/aimclub/GOLEM/pull/181/commits/d66e4a9aa2141d6974e835d6943e9c577781b7a8#diff-ea7cc5126ecede10ac12864ef00f36114d7f0fd9231fb4171f9cebf199042bfeR188)

2023-09-06 13:09 UTC, maypink commented on experiments/experiment_analyzer.py
> +        :param stat_tests: list of functions of statistical tests to perform.
[done](https://github.com/aimclub/GOLEM/pull/181/commits/d66e4a9aa2141d6974e835d6943e9c577781b7a8#diff-ea7cc5126ecede10ac12864ef00f36114d7f0fd9231fb4171f9cebf199042bfeR189)

2023-09-06 13:09 UTC, maypink commented on experiments/experiment_analyzer.py
> +        :param data_to_analyze: data to analyze. NB! data must have the specified format
а там речь про сам тип шла, [указала его еще раз в докстринге](https://github.com/aimclub/GOLEM/pull/181/commits/d66e4a9aa2141d6974e835d6943e9c577781b7a8#diff-ea7cc5126ecede10ac12864ef00f36114d7f0fd9231fb4171f9cebf199042bfeR188)

2023-09-06 13:12 UTC, maypink commented on experiments/experiment_analyzer.py
> +        """ Method to analyze specified metrics.
[done](https://github.com/aimclub/GOLEM/pull/181/commits/8615e060ce4721d10ff03a6febe5cc3fb23dbe6b#diff-ea7cc5126ecede10ac12864ef00f36114d7f0fd9231fb4171f9cebf199042bfeR102)

2023-09-06 13:13 UTC, maypink commented on experiments/experiment_analyzer.py
> +        """ Yields setup name, dataset name + paths to dirs with experiment results.
[done](https://github.com/aimclub/GOLEM/pull/181/commits/6f274bff5830af104bf4659851cb9a113868c4e9#diff-ea7cc5126ecede10ac12864ef00f36114d7f0fd9231fb4171f9cebf199042bfeR287)

2023-09-06 13:13 UTC, maypink commented on examples/experiment_analyzer/experiment_analyzer.py
> +    create_if_not_exists(path_to_save_metrics_boxplots)
[done](https://github.com/aimclub/GOLEM/pull/181/commits/6f274bff5830af104bf4659851cb9a113868c4e9#diff-ea7cc5126ecede10ac12864ef00f36114d7f0fd9231fb4171f9cebf199042bfeR45)

2023-09-06 13:14 UTC, maypink commented on experiments/experiment_analyzer.py
> +            result_dict[setup][dataset] = []
[done](https://github.com/aimclub/GOLEM/pull/181/commits/6f274bff5830af104bf4659851cb9a113868c4e9#diff-ea7cc5126ecede10ac12864ef00f36114d7f0fd9231fb4171f9cebf199042bfeR119)

2023-09-06 13:14 UTC, maypink commented on experiments/experiment_analyzer.py
> +                    dict_with_metrics[metric] = dict()
[done](https://github.com/aimclub/GOLEM/pull/181/commits/6f274bff5830af104bf4659851cb9a113868c4e9#diff-ea7cc5126ecede10ac12864ef00f36114d7f0fd9231fb4171f9cebf199042bfeR119)

2023-09-07 07:47 UTC, maypink commented
> Ещё можно пример данных в zip или tar.gz закатать и распаковывать уже на месте.

заархивировала и данные, и результаты. а с добавлением в FEDOT Web предлагаю разобраться на следующей итерации -- хочется уже влить и попользоваться

2023-09-11 14:43 UTC, YamLyubov commented on experiments/experiment_analyzer.py
> +        :param data_to_analyze: data to analyze. NB! data must have the specified format
Я скорее имела в виду, что по смыслу должно лежать в этом словаре. Или он у нас как-то сам по результатам запуска генерится?

2023-09-11 14:46 UTC, YamLyubov commented on experiments/experiment_analyzer.py
> +        """ Method to analyze specified metrics.
Строки тут результаты запуска?

2023-09-12 07:45 UTC, maypink commented on experiments/experiment_analyzer.py
> +        """ Method to analyze specified metrics.
в строках просто метрики, да. по идее, для этого и есть пример с данными, чтобы можно было посмотреть на формат более детально, если сходу по описанию непонятно

2023-09-12 08:00 UTC, maypink commented on experiments/experiment_analyzer.py
> +        :param data_to_analyze: data to analyze. NB! data must have the specified format
да, в `analyze_statistical_significance` передаются результаты из методов `analyze_convergence` или `analyze_metrics`, например. ну там написано в докстринге это

энивэй [описала еще по смыслу](https://github.com/aimclub/GOLEM/pull/181/commits/da34b8d28d7d113073f0cdcfe3da785d9d5da0c0#diff-ea7cc5126ecede10ac12864ef00f36114d7f0fd9231fb4171f9cebf199042bfeR191)

2023-09-12 08:23 UTC, YamLyubov approved these changes

2023-09-12 09:48 UTC, merged