Add ObjectiveInfo to OptHistory
aimclub/GOLEM pull request #19
Opened 2022-12-27 07:01 UTC by gkirgizov

Fixes #6

2022-12-29 09:12 UTC, MorrisNein requested changes
Сделано хорошо, есть небольшие замечания по читаемости.

Ещё предложения:
1) добавить проверку новых полей в тесты старых и новых историй
2) обеспечить обратную совместимость со старыми историями

2023-01-12 14:46 UTC, gkirgizov commented on golem/core/optimisers/objective/objective.py
> +        return ObjectiveInfo(self.is_multi_objective, self.metric_names)
Он каждый раз создает новый объект, а не возвращает какое-то неотъемлемое свойство истории. Дело вкуса, пожалуй, но мне нравится акцент на том, что это вызов

2023-01-12 14:51 UTC, gkirgizov commented on golem/core/optimisers/objective/objective.py
> +        fitness_info_str = [f'{name}={value:.3f}' for name, value in fitness_info]
Согласен, звучит разумно, можно было бы сделать и так, но это потреует множество изменений без каки-либо функциональных преимуществ. А это совсем спомогательный метод.

Перенести в Fitness тоже можно бы, но тогда использования этого метода будут менее удобными так как они нужны лдя списков фитнесов и единственного ObjectiveInfo.

2023-01-19 12:05 UTC, gkirgizov commented
>     1. добавить проверку новых полей в тесты старых и новых историй
Ты имеешь ввиду какие-то конкретные тесты? Не очень понял, зачем и для каких историй считаешь нужным это проверить

>     2. обеспечить обратную совместимость со старыми историями
Здесь https://github.com/aimclub/GOLEM/pull/19/commits/997566f569866b4db107b5e990611afd813cb827
Со старыми историями -- котоеы были с полем is_multi_objective?

2023-01-23 08:51 UTC, MorrisNein requested changes

2023-01-23 08:51 UTC, MorrisNein commented on golem/serializers/coders/opt_history_serialization.py
> +        del json_obj['_is_multi_objective']
Здесь ещё может быть вариант, что придёт старая история с Objective, а не Objective Info. Я бы проверил на usinstance ещё, и переводил в ObjectiveInfo в таком случае.

2023-01-23 08:53 UTC, gkirgizov commented
> > Ты имеешь ввиду какие-то конкретные тесты? Не очень понял, зачем и для каких историй считаешь нужным это проверить
> 
> Во-первых, для новых историй включить проверку нового поля в [этот тест](https://github.com/aimclub/GOLEM/blob/d8c8cfa416e8d8497babbce93cfe772da3e39e4d/test/unit/optimizers/test_composing_history.py#L230-L254).
> 
> Во-вторых, для старых историй: я думал, мы утащили в Голема [этот тест](https://github.com/aimclub/FEDOT/blob/4a6cf0f37d35b3eb76d9b2fb3d3775d099e0462d/test/unit/composer/test_history.py#L232-L253). Теперь вижу, что нет. Тогда можем добавить его даже отдельным PR и тоже включить проверку нового поля.

Старые истории с Pipeline не загрузить в GOLEM тк она содержит федотовские классы. В федоте добавлю эту строчку при переезде.

2023-01-23 08:55 UTC, gkirgizov commented on golem/serializers/coders/opt_history_serialization.py
> +        del json_obj['_is_multi_objective']
в этом случае не должно быть проблемы, тк Objective это подкласс ObjectiveInfo, и вызов методов должен пройти верно

2023-01-23 08:57 UTC, MorrisNein approved these changes

2023-01-23 08:59 UTC, merged