Multiline refactor
aimclub/GOLEM pull request #195
Opened 2023-09-18 08:35 UTC by YamLyubov

WIP

2023-10-02 09:47 UTC, pep8speaks commented
Hello @YamLyubov! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`examples/molecule_search/guacamol_benchmark.py`](https://github.com/aimclub/GOLEM/blob/a5067ce771f79a81ca6ad9df4f13f062a8fcdcb4/examples/molecule_search/guacamol_benchmark.py):

> [Line 33:121](https://github.com/aimclub/GOLEM/blob/a5067ce771f79a81ca6ad9df4f13f062a8fcdcb4/examples/molecule_search/guacamol_benchmark.py#L33): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (149 > 120 characters)



* In the file [`examples/synthetic_graph_evolution/generators.py`](https://github.com/aimclub/GOLEM/blob/a5067ce771f79a81ca6ad9df4f13f062a8fcdcb4/examples/synthetic_graph_evolution/generators.py):

> [Line 1:1](https://github.com/aimclub/GOLEM/blob/a5067ce771f79a81ca6ad9df4f13f062a8fcdcb4/examples/synthetic_graph_evolution/generators.py#L1): [F401](https://duckduckgo.com/?q=pep8%20F401) 'random' imported but unused

* In the file [`examples/synthetic_graph_evolution/graph_search.py`](https://github.com/aimclub/GOLEM/blob/a5067ce771f79a81ca6ad9df4f13f062a8fcdcb4/examples/synthetic_graph_evolution/graph_search.py):

> [Line 11:1](https://github.com/aimclub/GOLEM/blob/a5067ce771f79a81ca6ad9df4f13f062a8fcdcb4/examples/synthetic_graph_evolution/graph_search.py#L11): [F401](https://duckduckgo.com/?q=pep8%20F401) 'golem.core.log.Log' imported but unused
> [Line 21:1](https://github.com/aimclub/GOLEM/blob/a5067ce771f79a81ca6ad9df4f13f062a8fcdcb4/examples/synthetic_graph_evolution/graph_search.py#L21): [F401](https://duckduckgo.com/?q=pep8%20F401) 'golem.core.optimisers.random.random_mutation_optimizer.PopulationalRandomMutationOptimizer' imported but unused



* In the file [`golem/core/optimisers/adaptive/mab_agents/mab_agent.py`](https://github.com/aimclub/GOLEM/blob/a5067ce771f79a81ca6ad9df4f13f062a8fcdcb4/golem/core/optimisers/adaptive/mab_agents/mab_agent.py):

> [Line 68:9](https://github.com/aimclub/GOLEM/blob/a5067ce771f79a81ca6ad9df4f13f062a8fcdcb4/golem/core/optimisers/adaptive/mab_agents/mab_agent.py#L68): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable 'processed_rewards' is assigned to but never used







* In the file [`golem/core/optimisers/random/random_mutation_optimizer.py`](https://github.com/aimclub/GOLEM/blob/a5067ce771f79a81ca6ad9df4f13f062a8fcdcb4/golem/core/optimisers/random/random_mutation_optimizer.py):

> [Line 1:1](https://github.com/aimclub/GOLEM/blob/a5067ce771f79a81ca6ad9df4f13f062a8fcdcb4/golem/core/optimisers/random/random_mutation_optimizer.py#L1): [F401](https://duckduckgo.com/?q=pep8%20F401) 'random.choice' imported but unused

* In the file [`golem/core/optimisers/random/random_search.py`](https://github.com/aimclub/GOLEM/blob/a5067ce771f79a81ca6ad9df4f13f062a8fcdcb4/golem/core/optimisers/random/random_search.py):

> [Line 37:25](https://github.com/aimclub/GOLEM/blob/a5067ce771f79a81ca6ad9df4f13f062a8fcdcb4/golem/core/optimisers/random/random_search.py#L37): [E131](https://duckduckgo.com/?q=pep8%20E131) continuation line unaligned for hanging indent

* In the file [`golem/visualisation/opt_history/fitness_line.py`](https://github.com/aimclub/GOLEM/blob/a5067ce771f79a81ca6ad9df4f13f062a8fcdcb4/golem/visualisation/opt_history/fitness_line.py):

> [Line 5:1](https://github.com/aimclub/GOLEM/blob/a5067ce771f79a81ca6ad9df4f13f062a8fcdcb4/golem/visualisation/opt_history/fitness_line.py#L5): [F401](https://duckduckgo.com/?q=pep8%20F401) 'typing.TYPE_CHECKING' imported but unused

2023-10-04 11:23 UTC, maypink requested changes

2023-10-04 11:23 UTC, maypink commented on examples/synthetic_graph_evolution/experiment_setup.py
> +        file_name = f'{optimizer_cls.__name__[:-9]}_{graph_name}_n{num_nodes}_iter{trial_iterations}'
это так слово `Optimizer` вырезается? или почему именно 9

2023-10-04 11:23 UTC, maypink commented on examples/synthetic_graph_evolution/generators.py
> +    g = nx.gnp_random_graph(n, p=0.5, directed=True)
там чел в комментах к этому решению писал, что на супер больших графах оно ломается. нам-то не принципиально, но пометку я бы оставила

2023-10-04 11:23 UTC, maypink commented on golem/core/optimisers/random/random_mutation_optimizer.py
> +    """
я на написала побольше текста про то зачем такой оптимизатор и, например, где он был использован

2023-10-04 11:23 UTC, maypink commented on golem/visualisation/opt_history/multiple_fitness_line.py
> +                 metric_names,
тип

2023-10-04 11:23 UTC, maypink commented on golem/visualisation/opt_history/multiple_fitness_line.py
> +    def from_saved_histories(experiment_folders: List[str], root_path: os.PathLike):
тип того, что возвращает

2023-10-05 11:46 UTC, YamLyubov commented on examples/synthetic_graph_evolution/experiment_setup.py
> +        file_name = f'{optimizer_cls.__name__[:-9]}_{graph_name}_n{num_nodes}_iter{trial_iterations}'
Абсолютно точно)))

2023-10-05 12:03 UTC, YamLyubov commented on examples/synthetic_graph_evolution/generators.py
> +    g = nx.gnp_random_graph(n, p=0.5, directed=True)
[Done](https://github.com/aimclub/GOLEM/pull/195/files#diff-f73d9b77846460c4473a5f5b5cb6bba43430371d0a6e4acdb51f29302d078f71R28)

2023-10-05 12:05 UTC, maypink approved these changes

2023-10-05 12:05 UTC, maypink commented on .readthedocs.yml
> +build:
бтв кажется, оно уже заработало и без этого

2023-10-05 12:26 UTC, merged