Plot of agent mutations probabilities and actions expectations
aimclub/GOLEM pull request #197
Opened 2023-09-18 13:39 UTC by maypink

WIP

2023-09-19 12:44 UTC, maypink commented
Теперь можно делать такие картинки для каждой из метрик.
![sp_lapl](https://github.com/aimclub/GOLEM/assets/57305249/56580b85-c419-499d-80f6-782a244d47ad)
![degree](https://github.com/aimclub/GOLEM/assets/57305249/1472afa0-2986-418a-a6d6-cfecb4be05a8)
![graph_size](https://github.com/aimclub/GOLEM/assets/57305249/087cdd09-b7a5-40f8-8873-7374d9b73d36)
![sp_adj](https://github.com/aimclub/GOLEM/assets/57305249/f73012dd-be61-4319-abda-c6e0207c7659)

2023-10-03 09:57 UTC, YamLyubov requested changes

2023-10-03 09:57 UTC, YamLyubov commented on experiments/experiment_analyzer.py
> +                            path_to_save: str = None, is_raise: bool = False,
Здесь скорее всего имелось в виду `path_to_save: Optional[str] = None`

2023-10-03 09:57 UTC, YamLyubov commented on experiments/experiment_analyzer.py
> +
Может получится эти условия как-то объединить?

2023-10-03 09:57 UTC, YamLyubov commented on experiments/experiment_analyzer.py
>          :param path_to_save: path to save results.
Я бы добавила, что подразумевается именно папка для сохранения, а не путь к файлу

2023-10-03 09:57 UTC, YamLyubov commented on experiments/experiment_analyzer.py
> +        best_fitness_per_objective = [None] * metrics_num
Так как мы минимизируем метрику, то можно вместо None использовать np.inf - тогда не нужна будет проверка на None ниже

2023-10-03 09:57 UTC, YamLyubov commented on experiments/experiment_analyzer.py
> +                        path_to_save: str = None, is_raise: bool = False, keen_n_best: Optional[int] = 1) \
Здесь тоже typing подправить и опечатка в keen_n_best

2023-10-03 09:57 UTC, YamLyubov commented on experiments/experiment_analyzer.py
> +                all_metrics = list(df_metrics[metric])
Прикопаюсь: странное название all_metrics, если это на самом деле только одна метрика из нескольких

2023-10-03 09:57 UTC, YamLyubov commented on experiments/experiment_analyzer.py
> +        Must be > 1 when there were > 1 metric considered during the experiment.
Сранно, что > 1, если больше одной метрики. Суда по коду кажется, что это не имеет значения

2023-10-03 09:57 UTC, YamLyubov commented on experiments/experiment_analyzer.py
>          :param history_folder: name of the history folder in experiment result folder (e.g. 'history', 'histories')
Не хватает такого же замечания как в `analize_convergence`

2023-10-03 09:57 UTC, YamLyubov commented on experiments/experiment_analyzer.py
> +            if dataset != 'tree_100':
Затесалось)

2023-10-04 11:04 UTC, maypink commented on experiments/experiment_analyzer.py
> +                        path_to_save: str = None, is_raise: bool = False, keen_n_best: Optional[int] = 1) \
я просто киню n лучших решения

2023-10-05 11:44 UTC, maypink commented on experiments/experiment_analyzer.py
>          :param path_to_save: path to save results.
да вроде path_to_save это путь, а не папка

2023-10-05 12:00 UTC, pep8speaks commented
Hello @maypink! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`experiments/experiment_analyzer.py`](https://github.com/aimclub/GOLEM/blob/f0b0285da760da1a7c6803ea9277a8b69b208b9a/experiments/experiment_analyzer.py):

> [Line 227:121](https://github.com/aimclub/GOLEM/blob/f0b0285da760da1a7c6803ea9277a8b69b208b9a/experiments/experiment_analyzer.py#L227): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (124 > 120 characters)
> [Line 287:121](https://github.com/aimclub/GOLEM/blob/f0b0285da760da1a7c6803ea9277a8b69b208b9a/experiments/experiment_analyzer.py#L287): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)

2023-10-05 12:00 UTC, maypink commented on experiments/experiment_analyzer.py
> +                            path_to_save: str = None, is_raise: bool = False,
[done](https://github.com/aimclub/GOLEM/pull/197/commits/f0b0285da760da1a7c6803ea9277a8b69b208b9a#diff-ea7cc5126ecede10ac12864ef00f36114d7f0fd9231fb4171f9cebf199042bfeR40)

2023-10-05 12:00 UTC, maypink commented on experiments/experiment_analyzer.py
> +
[done](https://github.com/aimclub/GOLEM/pull/197/commits/f0b0285da760da1a7c6803ea9277a8b69b208b9a#diff-ea7cc5126ecede10ac12864ef00f36114d7f0fd9231fb4171f9cebf199042bfeR66)

2023-10-05 12:00 UTC, maypink commented on experiments/experiment_analyzer.py
>          :param path_to_save: path to save results.
[done](https://github.com/aimclub/GOLEM/pull/197/commits/f0b0285da760da1a7c6803ea9277a8b69b208b9a#diff-ea7cc5126ecede10ac12864ef00f36114d7f0fd9231fb4171f9cebf199042bfeR48)

2023-10-05 12:01 UTC, maypink commented on experiments/experiment_analyzer.py
> +        best_fitness_per_objective = [None] * metrics_num
[done](https://github.com/aimclub/GOLEM/pull/197/commits/f0b0285da760da1a7c6803ea9277a8b69b208b9a#diff-ea7cc5126ecede10ac12864ef00f36114d7f0fd9231fb4171f9cebf199042bfeR103)

2023-10-05 12:01 UTC, maypink commented on experiments/experiment_analyzer.py
> +                        path_to_save: str = None, is_raise: bool = False, keen_n_best: Optional[int] = 1) \
[done](https://github.com/aimclub/GOLEM/pull/197/commits/f0b0285da760da1a7c6803ea9277a8b69b208b9a#diff-ea7cc5126ecede10ac12864ef00f36114d7f0fd9231fb4171f9cebf199042bfeR126)

2023-10-05 12:01 UTC, maypink commented on experiments/experiment_analyzer.py
> +                all_metrics = list(df_metrics[metric])
[done](https://github.com/aimclub/GOLEM/pull/197/commits/f0b0285da760da1a7c6803ea9277a8b69b208b9a#diff-ea7cc5126ecede10ac12864ef00f36114d7f0fd9231fb4171f9cebf199042bfeR155)

2023-10-05 12:02 UTC, maypink commented on experiments/experiment_analyzer.py
> +        Must be > 1 when there were > 1 metric considered during the experiment.
[done](https://github.com/aimclub/GOLEM/pull/197/commits/f0b0285da760da1a7c6803ea9277a8b69b208b9a#diff-ea7cc5126ecede10ac12864ef00f36114d7f0fd9231fb4171f9cebf199042bfeR135)

2023-10-05 12:02 UTC, maypink commented on experiments/experiment_analyzer.py
>          :param history_folder: name of the history folder in experiment result folder (e.g. 'history', 'histories')
[done](https://github.com/aimclub/GOLEM/pull/197/commits/f0b0285da760da1a7c6803ea9277a8b69b208b9a#diff-ea7cc5126ecede10ac12864ef00f36114d7f0fd9231fb4171f9cebf199042bfeR179)

2023-10-05 12:02 UTC, maypink commented on experiments/experiment_analyzer.py
> +            if dataset != 'tree_100':
[done](https://github.com/aimclub/GOLEM/pull/197/commits/f0b0285da760da1a7c6803ea9277a8b69b208b9a#diff-ea7cc5126ecede10ac12864ef00f36114d7f0fd9231fb4171f9cebf199042bfeL258)

2023-10-05 12:37 UTC, YamLyubov approved these changes

2023-10-09 09:27 UTC, merged