Parallel population processing
aimclub/GOLEM pull request #199
Opened 2023-09-19 11:48 UTC by kasyanovse

Предлагаю вариант ускорения работы с поколениями в `EvoGraphOptimizer`. Реализовано через параллельную работу на базе `joblib`.

Что изменено:
1. В некоторые операторы (`golem.core.optimisers.genetic.operators`) добавлена реализация параллельной обработки.
2. Методы `EvoGraphOptimizer._extend_population` и `EvoGraphOptimizer._reproduce` реализованы через многопоток.
3. Удален оператор `ReproductionController`.
4. Логика `ReproductionController` была перенесена в `EvoGraphOptimizer._reproduce` из-за своего сокращения и схожести с логикой `EvoGraphOptimizer._extend_population`, и его единственным использованием в `EvoGraphOptimizer`. Упоминания `ReproductionController` из библиотеки пока не вычищались.
5. `MAX_GRAPH_GEN_ATTEMPTS` заменена на `MAX_GRAPH_GEN_ATTEMPTS_AS_POP_SIZE_MULTIPLIER`, чтобы количество попыток зависело от требуемого размера поколения.

Результат: до 100% времени композиции потребляется 100% ресурсов процессора. Ускорение еще не замерял, но на небольших штучных прогонах оно составляет до 40% от всего времени работы `Fedot`. Падения качества композиции в штучных прогонах не зафиксировал.

2023-09-20 08:19 UTC, valer1435 commented on golem/core/optimisers/genetic/gp_optimizer.py
> +    def _reproduce(self, population: PopulationT, evaluator: EvaluationOperator) -> PopulationT:
Я правильно понимаю, что идея в том, чтобы объединить процесс мутации и оценки пайплайна? Получается какое-то совмещение в одном методе ответственности за мутацию и за оценку

2023-09-20 08:20 UTC, valer1435 commented
И какое поведение будет у новой реализации, если n_jobs=1? Будет вызываться Parallel с n_jobs=1? Вроде был отдельный Dispatcher под это

2023-09-20 08:29 UTC, kasyanovse commented on golem/core/optimisers/genetic/gp_optimizer.py
> +    def _reproduce(self, population: PopulationT, evaluator: EvaluationOperator) -> PopulationT:
Да. Тут две причины:
1. Собирать поколение сразу выполняя несколько проверок: что граф нормально мутировал, что он валиден, что на нем считается фитнес. Все равно все эти этапы проверки необходимо пройти, почему бы не сделать их за один раз?
2. Оценить графы за одно распараллеливание. Вариант с распараллеливанием для мутаций, сбором информации в один процесс, а затем новым распараллеливанием для оценки фитнеса выглядит ненужным усложнением.

2023-09-20 08:31 UTC, kasyanovse commented on golem/core/optimisers/genetic/gp_optimizer.py
> +    def _reproduce(self, population: PopulationT, evaluator: EvaluationOperator) -> PopulationT:
А в чем может быть проблема совмещения ответственности при мутациях и одновременном расчете фитнеса?

2023-09-20 08:44 UTC, kasyanovse commented
> И какое поведение будет у новой реализации, если n_jobs=1? Будет вызываться Parallel с n_jobs=1? Вроде был отдельный Dispatcher под это

Проблемой `Parallel с n_jobs=1` не является, потому что в таком случае код выполняется в том же потоке, в котором он вызывается. Проблему с `Dispatcher` буду фиксить если такой вариант распараллеливания зайдет.

2023-09-20 12:09 UTC, maypink requested changes

2023-09-20 12:09 UTC, maypink commented on golem/core/optimisers/genetic/gp_optimizer.py
> +    def _reproduce(self, population: PopulationT, evaluator: EvaluationOperator) -> PopulationT:
согласна с Валерой, ответственность между мутациями и оценкой лучше разделять, так как это два разных оператора и дебажить будет гораздо легче, если каждый из них будет отвечать только за свое. да, потеряем во времени из-за двойного поднятия всей инфраструктуры для распараллеливания, но что поделать. 

настоящие неприятности начнутся, когда индивид успешно смутирует, но не оценится ввиду своей некорректности (которая не может быть полностью проверена верифаером)/неподходящей метрики. а источник у этого всего будет один -- отлаживать будет уже не так удобно, как сейчас.

2023-09-20 12:17 UTC, maypink commented
насчет `ReproductionController`: в моем понимании, это класс, ответственный за один эволюционный цикл. да, как ты правильно подметил, сейчас он есть только в `EvoGraphOptimizer`. 

Но GOLEM позиционируется, как универсальное решение, поэтому инфраструктура должна быть реализована по своего рода "строительным блокам". В таком случае, `ReproductionController` очень удобен, так как он делает один эволюционный цикл атомарным для оптимизатора и + вынесение этой логики в отдельный класс делает `EvoGraphOptimizer` чище -- в нем находятся только те методы, за которые должен нести ответственность непосредственно оптимизатор. 

Also, [здесь ](https://github.com/aimclub/GOLEM/pull/104) Гриша писал про мотивацию делать ReproductionController

2023-09-20 12:54 UTC, kasyanovse commented on golem/core/optimisers/genetic/gp_optimizer.py
> +                                                                 include_population_to_new_population=False)
Он нужен для того, чтобы по разному отрабатывать мутации для начального поколения и для последующих.

2023-09-20 13:03 UTC, kasyanovse commented on golem/core/optimisers/genetic/gp_optimizer.py
> +            # TODO: `new_ind.graph not in pop_graphs` in cycle has complexity ~N^2 (right?)
> n*log(n)

👍

2023-09-20 13:06 UTC, kasyanovse commented on golem/core/optimisers/genetic/gp_optimizer.py
> +            # TODO: `new_ind.graph not in pop_graphs` in cycle has complexity ~N^2 (right?)
> во всяком случае, в рамках этого пулл реквеста предлагаю не трогать сам механизм проверки структурной уникальности после мутации

Не трогать в смысле не трогать вот [этот](https://github.com/aimclub/GOLEM/blob/main/golem/core/optimisers/populational_optimizer.py#L99) код?

2023-09-20 13:09 UTC, kasyanovse commented on golem/core/optimisers/genetic/gp_optimizer.py
> +        def mutation_n_evaluation(individual: Individual,
То есть сам подход создать функцию перед ее применением не потиворечит кодстайлу библиотеки?

2023-09-20 13:11 UTC, kasyanovse commented on golem/core/optimisers/genetic/gp_optimizer.py
> +            for new_ind in new_ind_generator:
> может возникнуть некорректная ситуация, когда два потока с одинаковыми графами +- одновременно выполнят проверку в 170 строке

Не может, потому что вставка в `new_population` происходит в одном потоке.

2023-09-20 13:11 UTC, kasyanovse commented on golem/core/optimisers/genetic/gp_optimizer.py
> +            for new_ind in new_ind_generator:
> если же задумка была в том, чтобы каждый граф обрабатывался по готовности, то кмк будет работать быстрее, если поставить `return_as=generator_unordered` в параметры `Parallel`, так как каждый граф/индивид будет обрабатываться по мере готовности

Спасибо)) Моя ошибка)

2023-09-20 13:20 UTC, kasyanovse commented on golem/core/optimisers/genetic/operators/mutation.py
> +            mutation_result = [[x] for x in self._mutation(population)]
Да. Это одна из проблем реализованного подхода. По идее, что-то похожее надо будет сделать везде, где используется `n_jobs` из `GraphRequirements`, потому что может возникнуть ситуация когда в мультипотоке разворачивается мультипоток.
Пока не знаю как это сделать красиво и эффективно. Такой вариант нормален?

2023-09-20 13:32 UTC, kasyanovse commented on golem/core/optimisers/genetic/gp_optimizer.py
> +    def _reproduce(self, population: PopulationT, evaluator: EvaluationOperator) -> PopulationT:
Согласен, однако на одной чаше весов скорость выполнения (которую еще замерить надо))) для любого пользователя голема, а на другой - отладка, которой занимаются не так уж и много человек.

Для целей отладки можно все неудавшиеся экземпляры хранить в отдельном объекте с пометкой на каком этапе он отсеялся. Так для отладки будет удобней, потому что все они в одном месте, рассортированные по типу проблемы (можно даже отладочные инструменты поверх этого объекта сразу накрутить), и пользователям будет ок, потому что у них будет один непрекращающийся мультипоток.

Что скажете?

2023-09-21 06:38 UTC, kasyanovse commented
Я не против вернуть `ReproductionController`. С учетом имеющихся правок такое решение приведет к почти полному дублированию функционала, используемого для набора начальной популяции. Если процесс воспроизводства поколения сейчас реализован нормально и не требует существенных корректировок, то как воссоздать `ReproductionController`? Да и в целом, необходимость полного дублирования говорит о том, что отдельный модуль, скорее всего, не нужен.

> Also, [здесь ](https://github.com/aimclub/GOLEM/pull/104) Гриша писал про мотивацию делать ReproductionController

Новый код удовлетворяет задаче, решаемой [здесь](https://github.com/aimclub/GOLEM/pull/104), и в то же время смягчает недостатки подхода, предложенного там же. Единственное, что отладка не такая удобная, но у меня есть пара предложений как это можно решить, не теряя в производительности. Ну и оценить корректность реализации я могу лишь с натяжкой.

Небольшое резюме (субъективное):
Если вернуть `ReproductionController`:
1. Плюсы
    1. Является универсальным строительным блоком
1. Минусы
    1. Большая часть функционала (логического) дублирует аналогичный функционал в `EvoGraphOptimizer` (набор начального поколения)
    2. Не востребован как универсальный блок на текущий момент
    3. Логически он отнесен к `operators`, однако:
        1. В `EvoGraphOptimizer` он не сохраняется в  `EvoGraphOptimizer.operators` (для него не обновляются `requirements`)
        2. Он сам использует другие `operators` внутри себя
        3. Его интерфейс отличается от других `operators`

Если не возвращать `ReproductionController`:
1. Плюсы
    1. Меньше кода, меньше проблем, проще структура
    4. Меньше дублирования кода или функциональности
1. Минусы
    1. Отсутствие универсального строительного блока

Свлю точку зрения я пояснил (надеюсь))), однако я не погружен в GOLEM, не знаю как будет оптимальней с точки зрения развития библиотеки. Сделаю как ты посчитаешь правильным)

2023-09-21 06:48 UTC, kasyanovse commented on golem/core/optimisers/genetic/gp_optimizer.py
> +            for new_ind in new_ind_generator:
>  `return_as=generator_unordered` 

Настолько свежая фича, что ее еще в PyPi нет) А в документации уже есть.

2023-09-26 12:56 UTC, pep8speaks commented
Hello @kasyanovse! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`golem/core/optimisers/genetic/gp_optimizer.py`](https://github.com/aimclub/GOLEM/blob/0f4f7f5a3fff6527f3ec575bd6d2add840006398/golem/core/optimisers/genetic/gp_optimizer.py):

> [Line 2:1](https://github.com/aimclub/GOLEM/blob/0f4f7f5a3fff6527f3ec575bd6d2add840006398/golem/core/optimisers/genetic/gp_optimizer.py#L2): [F401](https://duckduckgo.com/?q=pep8%20F401) 'time.perf_counter' imported but unused

2023-10-17 13:49 UTC, maypink requested changes

2023-10-17 13:49 UTC, maypink commented on golem/core/optimisers/genetic/gp_optimizer.py
> +            new_population, pop_graphs = population[:], set([ind.graph.descriptive_id for ind in population])
там же лежат descriptive_id, а не графы. в таком случае это `pop_graph_idxs`

2023-10-17 13:49 UTC, maypink commented on golem/core/optimisers/genetic/gp_optimizer.py
> +            new_population, pop_graphs = population[:], set([ind.graph.descriptive_id for ind in population])
то есть если include_population_to_new_population == True, то мы проверяем измененную популяцию на уникальность `descriptive_id`? кажется, что-то не сходится. какой смысл ты закладывал в эту переменную?

2023-10-17 13:49 UTC, maypink commented on golem/core/optimisers/genetic/gp_optimizer.py
> +                                  mutation: Mutation = self.mutation,
а зачем здесь мтуация и верфаер в параметрах функции? вроде это базовый функционал, которому не нужна такая гибкость

2023-10-17 13:49 UTC, maypink commented on golem/core/optimisers/genetic/gp_optimizer.py
> +        if 0 < len(new_population) < target_pop_size:
куда-то делось `_minimum_valid_ratio`. можно сделать его меньше, чем было раньше (чем 50%)

2023-10-17 14:00 UTC, maypink commented on golem/core/optimisers/genetic/operators/mutation.py
> +            mutation_result = [[x] for x in self._mutation(population)]
да, думаю ок

2023-10-17 14:08 UTC, kasyanovse commented on golem/core/optimisers/genetic/gp_optimizer.py
> +                                  mutation: Mutation = self.mutation,
1. Явное определение всех нужных параметров внутри пространства имен функции.
2. Чтобы при распараллеливании они сразу копировались вместе с функцией, а не искались потом по пространствам имен.

Если плохо смотрится, то могу переписать по другому.

2023-10-17 14:16 UTC, kasyanovse commented on golem/core/optimisers/genetic/gp_optimizer.py
> +            new_population, pop_graphs = population[:], set([ind.graph.descriptive_id for ind in population])
Смысл состоит во включении в формируемое поколение исходного поколения.
Измененная популяция всегда проверятся на уникальность `descriptive_id`.

2023-10-17 14:18 UTC, kasyanovse commented on golem/core/optimisers/genetic/gp_optimizer.py
> +        if 0 < len(new_population) < target_pop_size:
Честно говоря, я не совсем понял смысл `_minimum_valid_ratio`. Функционально он ни на что не влиял, просто сигнализировал, что какие-то проблемы.
Вернуть его для сигнализации?

2023-10-17 15:25 UTC, kasyanovse commented
> я только за мультипроцессинг здесь, но надо понимать, насколько большой выигрыш мы заимеем, если откажемся от ООП в виде `ReproductionController`. Как мимнимум, предлагаю померить ускорение с изменениями в этом ПР и без, и, возможно, с последовательным распараллеливанием дважды для мутации и оценки, чтобы не терять ни в чем архитектурно. Если получится, что при однократном открывании потока мы действительно станем намного быстрее, тогда откажемся от репродукции в отдельном классе.


Само по себе двойное распараллеливание не даст сильной просадки по времени в обычном случае (недавно прочитал). `joblib` по умолчанию не глушит потоки после окончания расчетов, а ждет новых заданий.

Насчет возврата `ReproductionController` и старой структуры есть варианты:

1. Оставить `ReproductionController`, сделать в нем мутации параллельно.
Внутри `ReproductionController` мутации вызываются в цикле и проблема одного тупящего потока (когда последний поток что-то долго считает после того, как завершились остальные) может значительно снизить эффект от распараллеливания. Плюс к тому некоторый функционал останется нераспараллеленым.

1. Переписать `ReproductionController` по типу того, что сейчас сделано в этом PR. В таком случае логика `ReproductionController` сократится до пары десятков строк. Насколько целесообразно оставлять класс, который будет частично дублировать функционал, реализованный в `EvoGraphOptimizer._extend_population` и состоять из пары десятков строк? Проблема одного тупящего потока будет в два раза актуальнее, чем при текущей реализации, так как многопоток будет разворачиваться два раза.

1. Отказаться от `ReproductionController`, а его функционал частично объединить с `EvoGraphOptimizer._extend_population` и выделить в отдельную функцию. Что и было сделано. При этом:
    1. Упрощение
        2. На один модуль меньше, на один класс меньше.
        3. `EvoGraphOptimizer._extend_population` упростилась.
    5. Ускорение за счет:
        6. Объединения двух из трех вложенных циклов при мутациях в поколениях (три цикла - один на уровне `ReproductionController`, внутри него мутации в цикле по поколению, внутри каждой мутации еще один цикл)
        7. Распараллеливания
        8. При решении #205 и выносе цикла из мутаций на уровень поколения, будет ускорение за счет уменьшения длительности распараллеленного функционала.
    В этом случае речь идет не только о скорости распараллеливания, но и о том, что сама структура `EvoGraphOptimizer` в этом PR проще (ИМХО) и годится для решения #205 (а это дополнительное ускорение).

2023-11-02 03:14 UTC, maypink requested changes

2023-11-02 03:14 UTC, maypink commented on golem/core/optimisers/genetic/operators/reproduction.py
> +            # rebuild population due to problem with changing id of individuals in parallel individuals building
а в чем проблема, как id'шники меняются?

2023-11-02 03:14 UTC, maypink commented on golem/core/optimisers/genetic/operators/mutation.py
> +        final_population = []
почему поменял то, как было? с постпроцессингом хотя бы

2023-11-02 03:14 UTC, maypink commented on golem/core/optimisers/genetic/operators/reproduction.py
> +                             tries: int = self.parameters.max_num_of_mutation_attempts):
напиши пж сразу что здесь возвращается, чтобы бы пр смотреть попроще

2023-11-02 03:14 UTC, maypink commented on golem/core/optimisers/genetic/operators/reproduction.py
> +            return 1, individual, mutation_type, tries - 1
надо для failed stages Enum сразу сделать, чтобы были говорящие имена

2023-11-02 06:19 UTC, kasyanovse commented on golem/core/optimisers/genetic/operators/crossover.py
> +            new_population = population[:]
Чтобы в обоих условиях `if` возвращать новый список.

2023-11-02 06:23 UTC, kasyanovse commented on golem/core/optimisers/genetic/operators/reproduction.py
> +            # rebuild population due to problem with changing id of individuals in parallel individuals building
В мультипотоке индивиды копируются в каждый поток, то есть имеют `id`, отличные от тех, что в основном потоке. При создании новых индивидов в параллельном потоке, в них прописываются родители с `id`, соответствующими многопоточным копиям, а не оригиналам.

Есть юнит тест, который проверяет корректность `id` индивидов в поколениях. Не знаю зачем, но, видимо, это важно))

2023-11-02 06:28 UTC, kasyanovse commented on golem/core/optimisers/genetic/operators/mutation.py
> +        final_population = []
С постпроцессингом?

2023-11-02 06:31 UTC, kasyanovse commented on golem/core/optimisers/genetic/operators/reproduction.py
> +            return 1, individual, mutation_type, tries - 1
Хорошая идея. Попробую, но не гарантирую, что сработает.
Например, если возвращать строки, а не `int`, то потоки иногда падают. Редко, но стабильно. Три дня смотрел на эту ошибку и решил сделать так.

2023-11-02 13:00 UTC, kasyanovse commented on golem/core/optimisers/genetic/operators/reproduction.py
> +            return 1, individual, mutation_type, tries - 1
Тестирую.

2023-11-03 12:25 UTC, YamLyubov requested changes

2023-11-03 12:25 UTC, YamLyubov commented on golem/core/optimisers/genetic/operators/mutation.py
> +class SinglePredefinedMutation(Mutation):
Не совсем понимаю, зачем нужен этот класс. Только он используется в `ReproductionController`. По факту получается, что код `Mutation` вообще не используется

2023-11-03 12:25 UTC, YamLyubov commented on golem/core/optimisers/genetic/operators/reproduction.py
> +            mutation = SinglePredefinedMutation(parameters=self.mutation.parameters,
Почему нельзя использовать просто `Mutation`? В нем уже заложена логика[ повторного применения мутации в случае неудачи ](https://github.com/aimclub/GOLEM/blob/main/golem/core/optimisers/genetic/operators/mutation.py#L99)

2023-11-03 12:25 UTC, YamLyubov commented on golem/core/optimisers/genetic/operators/reproduction.py
> +            while left_tries > 0:
Я не очень знакома с многопоточностью, но возможно получится сделать здесь цикл `for _ in range(len(population))`? while довольно долго работает, да и мне кажется так будет понятнее, что в цикле происходит. Если использовать класс `Mutation` (в котором уже есть логика повторной попытки), можно будет избавиться от параметра `MAX_GRAPH_GEN_ATTEMPTS_PER_IND`

2023-11-03 12:25 UTC, YamLyubov commented on golem/core/optimisers/genetic/operators/reproduction.py
> +                if future._state == 'FINISHED':
Может использовать `future.done() and not future.cancelled()`, чтобы не обращаться к protected атрибуту?

2023-11-03 12:31 UTC, kasyanovse commented on golem/core/optimisers/populational_optimizer.py
> -    def get_structure_unique_population(self, population: PopulationT, evaluator: EvaluationOperator) -> PopulationT:
Сейчас проверка уникальности индивидов осуществляется при их создании. Третий этап в `_mutation_n_evaluation`.

2023-11-03 12:42 UTC, kasyanovse commented on golem/core/optimisers/genetic/operators/reproduction.py
> +            mutation = SinglePredefinedMutation(parameters=self.mutation.parameters,
Для ускорения. `Mutation` нередко зависает в попытках применить одну и ту же мутацию (по умолчанию стоит 100 итераций), при этом часто он сам себе палки в колеса вставляет, не применяя некоторые мутации по случайному флагу. Упрощенные мутации без повторения, повторяются в многопотоке, а не в цикле внутри одного потока, что, в теории, должно ускорять процесс.

2023-11-03 12:45 UTC, kasyanovse commented on golem/core/optimisers/genetic/operators/reproduction.py
> +            while left_tries > 0:
Можно, но как, чтобы это было эффективно?
ПС. Как видно по юнит тестам, мой подход оказался неэффективен((

2023-11-14 14:46 UTC, nicl-nno commented
FYI:

https://github.com/aimclub/GEFEST/pull/70
Вот тут этот PR обсуждался, мб что-то полезное можно сразу учесть. Не обязательно все сразу.

2023-12-07 13:23 UTC, kasyanovse commented
Move to https://github.com/aimclub/GOLEM/pull/247

2023-12-07 13:23 UTC, closed without merging