Add tuners
aimclub/GOLEM pull request #21
Opened 2023-01-18 13:48 UTC by YamLyubov

Main changes
- ``SequentialTuner`` abstracted to general graph
- ``PipelineTuner`` abstracted to general graph and renamed to ``SimultaniousTuner`` 
- ``SearchSpace`` abstracted to general graph
- ``structure`` parameter added to ``Graph``
- ``parameters`` parameter added to ``LinkedGraphNode``
- ``ObjectiveEvaluate.eval_n_jobs`` made public to allow tuners to reset it

2023-01-19 13:15 UTC, gkirgizov requested changes

2023-01-19 13:15 UTC, gkirgizov commented on test/unit/tuning/test_tuning.py
> +    assert init_metric <= final_metric
в остальном тесты хороши

2023-01-19 13:15 UTC, gkirgizov commented on golem/core/tuning/search_space.py
> +        self.parameters_per_operation = search_space
Предлагаю доавить описание формата этого словаря в док-коммент, иначе неясно, что передавать.
Также поможет полное определение типа (не dict, а Dict[...])

2023-01-24 10:35 UTC, YamLyubov commented on golem/core/dag/graph.py
> +
[Добавила](https://github.com/aimclub/GOLEM/pull/21/files#diff-0f0147bcdfd2af4de15a8301f6bdfb403442cee76a4697c39731c6e12b6cb751R239)

2023-01-24 10:35 UTC, YamLyubov commented on golem/core/dag/linked_graph_node.py
> +            self.content['params'] = {**self.content['params'], **new_parameters}
[Исправила](https://github.com/aimclub/GOLEM/pull/21/files#diff-55392eabd28af9351abcf0a09c006f1914ef1dc14598743aad8f458d25c07de5R53)

2023-01-24 10:36 UTC, YamLyubov commented on golem/core/optimisers/objective/objective_eval.py
> +        self.eval_n_jobs = eval_n_jobs
[Сделано](https://github.com/aimclub/GOLEM/pull/21/files#diff-c45438432ce98aea73d1a873742c3f81739d4aee4b270dde2fe9d2d742c64146R35)

2023-01-24 10:37 UTC, YamLyubov commented on golem/core/tuning/simultanious_tuning.py
> +class SimultaniousTuner(HyperoptTuner):
[Исправила везде)](https://github.com/aimclub/GOLEM/pull/21/files#diff-ec1876ed94dff4e8711dd27a7b3715bb2ffd466ade11951edc97133e32bd1791R13)

2023-01-24 10:38 UTC, YamLyubov commented on golem/core/tuning/tuner_interface.py
> +        deviation = (self.init_metric / 100.0) * 0.05
[Вынесла](https://github.com/aimclub/GOLEM/pull/21/files#diff-1f87812e47ef7b23a646340370b8f700524fb1ac518fce5804e47cd5929b0211R45)

2023-01-24 10:42 UTC, YamLyubov commented on requirements.txt
> +
Изначально скопировала эту зависимость из федота. Не думаю, что будут новые версии выходить, но поставила [менее строгое требование](https://github.com/aimclub/GOLEM/pull/21/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R25). Можно и для более ранних версий протестировать, если нужно

2023-01-24 10:42 UTC, YamLyubov commented on test/unit/tuning/test_tuning.py
> +    assert init_metric <= final_metric
[Разбила](https://github.com/aimclub/GOLEM/pull/21/files#diff-64fefe154daa50f8ed12f4c0e0163282dee2d3572db0b5f86b0940a4dec0c880R42)

2023-01-24 10:43 UTC, YamLyubov commented on golem/core/tuning/search_space.py
> +        self.parameters_per_operation = search_space
[Добавила](https://github.com/aimclub/GOLEM/pull/21/files#diff-479b583d77e0bdc1448734ca7241a3093b42442f2c6a8a2ad5aaf1b96945c4b1R7)

2023-01-24 10:45 UTC, YamLyubov commented
Еще перенесла изменения для тюнера [из этого пр](https://github.com/aimclub/FEDOT/pull/1019) сюда

2023-01-25 07:25 UTC, gkirgizov commented on golem/core/dag/graph.py
> +
Чем она отличается от Graph.descriptive_id, от str, от repr? Почему есть необходимость в новом методе?

```
    @property
    def descriptive_id(self) -> str:
        """Returns human-readable identifier of the graph.

        Returns:
            str: text description of the content in the node and its parameters
        """
```

2023-01-25 07:27 UTC, gkirgizov commented on golem/core/tuning/sequential.py
> +    def tune(self, graph: DomainStructureType) -> DomainStructureType:
Нужно унаследоваться от Generic[DomainStructureType]

2023-01-25 07:29 UTC, gkirgizov commented on requirements.txt
> +
понял, ранние не надо, так достаточно

2023-01-25 07:31 UTC, gkirgizov requested changes
Поправь еще пару оставшихся комментариев

2023-01-25 10:41 UTC, YamLyubov commented on golem/core/dag/graph.py
> +
[Вынесла](https://github.com/aimclub/GOLEM/pull/21/files#diff-a9919eed5feb46613e14614e46806a5c5a5e79ee3393acf7312cbd4d53aa104fR131) в graph_utils

2023-01-25 10:43 UTC, YamLyubov commented on golem/core/tuning/sequential.py
> +    def tune(self, graph: DomainStructureType) -> DomainStructureType:
[Исправила](https://github.com/aimclub/GOLEM/pull/21/files#diff-1f87812e47ef7b23a646340370b8f700524fb1ac518fce5804e47cd5929b0211R22)

2023-01-25 11:21 UTC, gkirgizov approved these changes

2023-01-25 12:07 UTC, merged