Fix crossover
aimclub/GOLEM pull request #212
Opened 2023-10-09 13:14 UTC by YamLyubov

WIP

2023-10-09 13:14 UTC, pep8speaks commented
Hello @YamLyubov! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`golem/core/optimisers/genetic/gp_operators.py`](https://github.com/aimclub/GOLEM/blob/dbd70664830b92d7237bd1eaca3c844ae94c3bc9/golem/core/optimisers/genetic/gp_operators.py):

> [Line 19:27](https://github.com/aimclub/GOLEM/blob/dbd70664830b92d7237bd1eaca3c844ae94c3bc9/golem/core/optimisers/genetic/gp_operators.py#L19): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 70:121](https://github.com/aimclub/GOLEM/blob/dbd70664830b92d7237bd1eaca3c844ae94c3bc9/golem/core/optimisers/genetic/gp_operators.py#L70): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (131 > 120 characters)

2023-10-10 10:19 UTC, maypink requested changes

2023-10-10 10:19 UTC, maypink commented on test/integration/test_evolution_with crossover.py
> +from functools import partial
в названии файла потерялось нижнее подчеркивание))

2023-10-10 10:19 UTC, maypink commented on test/integration/test_evolution_with crossover.py
> +    initial_graphs = [generate_labeled_graph('tree', i) for i in range(4, 20)]
сюда наверно тоже надо прокинуть `graph_type`, а не `tree` по дефолту

2023-10-10 10:19 UTC, maypink commented on test/unit/adapter/test_adapter.py
> +        root_node = [node for node, data in restored_graph.nodes(data='alpha', default=None) if data is not None][0]
почему просто не взять ноду с тем же индексом? судя по всему, в нетворксе они также идут в порядке обхода в глубину

2023-10-10 12:10 UTC, YamLyubov commented on test/integration/test_evolution_with crossover.py
> +from functools import partial
[Done](https://github.com/aimclub/GOLEM/pull/212/files#diff-f653ba988ca5db5ee7dbf91f36a1eb09b8b9740281932db85823c4313f659134R1)

2023-10-10 12:10 UTC, YamLyubov commented on test/integration/test_evolution_with crossover.py
> +    initial_graphs = [generate_labeled_graph('tree', i) for i in range(4, 20)]
[Done](https://github.com/aimclub/GOLEM/pull/212/files#diff-f653ba988ca5db5ee7dbf91f36a1eb09b8b9740281932db85823c4313f659134R51)

2023-10-10 12:11 UTC, YamLyubov commented on test/unit/adapter/test_adapter.py
> +        root_node = [node for node, data in restored_graph.nodes(data='alpha', default=None) if data is not None][0]
Сделал немного [читаемее ](https://github.com/aimclub/GOLEM/pull/212/files#diff-c6243c051099531433eba093320f3bdb559d2a8096dd9e2649a332a1b3072c69R37)

2023-10-19 12:06 UTC, merged