ExperimentLauncher
aimclub/GOLEM pull request #213
Opened 2023-10-09 14:15 UTC by maypink

2023-10-09 14:15 UTC, pep8speaks commented
Hello @maypink! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`examples/experiment_launcher/experiment_launcher.py`](https://github.com/aimclub/GOLEM/blob/45b339da915bfbb41ded14e89e49efe55c1afab2/examples/experiment_launcher/experiment_launcher.py):

> [Line 4:1](https://github.com/aimclub/GOLEM/blob/45b339da915bfbb41ded14e89e49efe55c1afab2/examples/experiment_launcher/experiment_launcher.py#L4): [F401](https://duckduckgo.com/?q=pep8%20F401) 'experiments.experiment_launcher.ExperimentLauncher' imported but unused



* In the file [`experiments/experiment_launcher.py`](https://github.com/aimclub/GOLEM/blob/45b339da915bfbb41ded14e89e49efe55c1afab2/experiments/experiment_launcher.py):

> [Line 6:1](https://github.com/aimclub/GOLEM/blob/45b339da915bfbb41ded14e89e49efe55c1afab2/experiments/experiment_launcher.py#L6): [F401](https://duckduckgo.com/?q=pep8%20F401) 'pathlib.Path' imported but unused
> [Line 50:13](https://github.com/aimclub/GOLEM/blob/45b339da915bfbb41ded14e89e49efe55c1afab2/experiments/experiment_launcher.py#L50): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable 'file_name' is assigned to but never used

2023-10-10 06:32 UTC, maypink commented
@YamLyubov посмотри пж на предмет того, универсально ли это дело, и будет ли тебе удобно запускаться так с молекулами, например

2023-10-10 11:52 UTC, YamLyubov requested changes

2023-10-10 11:52 UTC, YamLyubov commented on experiments/experiment_launcher.py
> +    def __init__(self, graph_names: List[str], graph_sizes: List[int], path_to_save: str,
`graph_names` ,  `graph_sizes` и `node_types` не являются универсальными.

2023-10-10 11:52 UTC, YamLyubov commented on experiments/experiment_launcher.py
> +                found_nx_graph = BaseNetworkxAdapter().restore(found_graph)
Получается эти эксперименты только для nx графов запускаются. Было бы удобнее более базовый класс иметь

2023-10-10 11:52 UTC, YamLyubov commented on experiments/experiment_launcher.py
> +    def _launch_experiment(self, graph_name: str, num_nodes: int, node_types: List[str], optimizer_setup: Callable):
Мне кажется, лучше использовать `@abstractmethod`

2023-10-10 11:52 UTC, YamLyubov commented on experiments/experiment_launcher.py
> +    def __init__(self, graph_names: List[str], graph_sizes: List[int], path_to_save: str,
Наверное тут и в `_experiment_launcher` придется kwargs сделать, для универсальности

2023-10-10 15:11 UTC, maypink commented on experiments/experiment_launcher.py
> +    def __init__(self, graph_names: List[str], graph_sizes: List[int], path_to_save: str,
done

2023-10-10 15:11 UTC, maypink commented on experiments/experiment_launcher.py
> +                found_nx_graph = BaseNetworkxAdapter().restore(found_graph)
done

2023-10-13 10:16 UTC, YamLyubov approved these changes

2023-10-13 11:35 UTC, merged