Tuner interface update
aimclub/GOLEM pull request #234
Opened 2023-10-30 11:59 UTC by YamLyubov

#232

2023-10-30 11:59 UTC, pep8speaks commented
Hello @YamLyubov! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`golem/core/tuning/iopt_tuner.py`](https://github.com/aimclub/GOLEM/blob/53d11621d411c12790f9a2c7313e98d605677077/golem/core/tuning/iopt_tuner.py):

> [Line 2:1](https://github.com/aimclub/GOLEM/blob/53d11621d411c12790f9a2c7313e98d605677077/golem/core/tuning/iopt_tuner.py#L2): [F401](https://duckduckgo.com/?q=pep8%20F401) 'itertools.chain' imported but unused





* In the file [`golem/core/tuning/simultaneous.py`](https://github.com/aimclub/GOLEM/blob/53d11621d411c12790f9a2c7313e98d605677077/golem/core/tuning/simultaneous.py):

> [Line 12:1](https://github.com/aimclub/GOLEM/blob/53d11621d411c12790f9a2c7313e98d605677077/golem/core/tuning/simultaneous.py#L12): [F401](https://duckduckgo.com/?q=pep8%20F401) 'golem.utilities.data_structures.ensure_wrapped_in_sequence' imported but unused

* In the file [`golem/core/tuning/tuner_interface.py`](https://github.com/aimclub/GOLEM/blob/53d11621d411c12790f9a2c7313e98d605677077/golem/core/tuning/tuner_interface.py):

> [Line 237:46](https://github.com/aimclub/GOLEM/blob/53d11621d411c12790f9a2c7313e98d605677077/golem/core/tuning/tuner_interface.py#L237): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 237:48](https://github.com/aimclub/GOLEM/blob/53d11621d411c12790f9a2c7313e98d605677077/golem/core/tuning/tuner_interface.py#L237): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals

2023-11-02 02:47 UTC, maypink requested changes

2023-11-02 02:47 UTC, maypink commented on golem/core/tuning/iopt_tuner.py
> +        has_parameters_to_optimize = (len(problem_parameters.discrete_parameters_names) > 0 or
не могу написать коммент к той строчке, тк она не затрагивается в пулл реквесте, но там выше в GolemProblem camelCase'ом пишутся названия полей, так и надо?

2023-11-02 02:47 UTC, maypink commented on golem/core/tuning/tuner_interface.py
> +    def _check_tuning_possible(self, graph: OptGraph,
_check_if_tuning_possible

2023-11-02 02:47 UTC, maypink commented on golem/core/tuning/tuner_interface.py
> +            remaining_time = self.timeout.seconds - tuner_timer.minutes_from_start * 60
поч просто не взять сразу `tuner_timer.seconds_from_start` вместо `tuner_timer.minutes_from_start * 60`?

2023-11-02 02:47 UTC, maypink commented on golem/core/tuning/optuna_tuner.py
> +            is_multi_objective = self.objectives_number > 1
если ты в 36 строчке явно указываешь, что `self.objectives_number = 1`, то наверно это doesn't make sense

2023-11-02 02:47 UTC, maypink commented on golem/core/tuning/sequential.py
> +        with Timer() as global_tuner_timer:
мб вынести в отедльный метод `_tune` этот внутренний цикл оптимизации гиперпараметров начиная с `with Timer() as global_tuner_timer:` ? вроде во всех тюнерах одна core логика -- мол если нельзя оптимизировать, то берем начальный граф и его адаптируем

2023-11-03 12:30 UTC, YamLyubov commented on golem/core/tuning/iopt_tuner.py
> +        has_parameters_to_optimize = (len(problem_parameters.discrete_parameters_names) > 0 or
В iOpt использовался camelCase, а так как мы наследуемся от их класса, то нам тоже придется. С переходом на новую версию iOpt это [исправится ](https://github.com/aimclub/GOLEM/pull/150)

2023-11-07 14:57 UTC, YamLyubov commented on golem/core/tuning/tuner_interface.py
> +    def _check_tuning_possible(self, graph: OptGraph,
[Done](https://github.com/aimclub/GOLEM/pull/234/files#diff-be29689607e6f62fd4cb9e1d70b9591b85b2afbde3f1558461c7ca1e6a1bd739R150)

2023-11-07 14:58 UTC, YamLyubov commented on golem/core/tuning/tuner_interface.py
> +            remaining_time = self.timeout.seconds - tuner_timer.minutes_from_start * 60
[Done](https://github.com/aimclub/GOLEM/pull/234/files#diff-1f87812e47ef7b23a646340370b8f700524fb1ac518fce5804e47cd5929b0211R275)

2023-11-07 14:59 UTC, YamLyubov commented on golem/core/tuning/optuna_tuner.py
> +            is_multi_objective = self.objectives_number > 1
В [этой строчке](https://github.com/aimclub/GOLEM/pull/234/files#diff-e23e4fc7d69c92ee979c50a1f0c09951d0a29876e8de90b3123858809b74e706R41) я это значение  переписываю

2023-11-07 15:00 UTC, YamLyubov commented on golem/core/tuning/sequential.py
> +        with Timer() as global_tuner_timer:
[Done](https://github.com/aimclub/GOLEM/pull/234/files#diff-1f87812e47ef7b23a646340370b8f700524fb1ac518fce5804e47cd5929b0211R94)

2023-11-27 09:33 UTC, maypink approved these changes

2023-11-27 11:43 UTC, merged