Fix mutation operator
aimclub/GOLEM pull request #238
Opened 2023-11-07 14:47 UTC by YamLyubov

WIP

2023-11-08 11:44 UTC, kasyanovse requested changes

2023-11-08 11:44 UTC, kasyanovse commented on golem/core/optimisers/genetic/operators/mutation.py
> +                if is_correct_graph and graph != new_graph:
1. [Проверка на уникальность](https://github.com/aimclub/GOLEM/blob/main/golem/core/optimisers/populational_optimizer.py#L97) графов осуществляется выше по стеку, на этапе композера раз в 5 поколений.
2. Как будто бы проверка внутри каждой мутации может замедлить композицию.

Стоит ли сравнивать графы тут или не стоит - не знаю. Может быть чуть позже потеструю у себя и скажу что по скорости.

2023-11-08 11:44 UTC, kasyanovse commented on golem/core/optimisers/genetic/operators/mutation.py
> +            for _ in range(self.parameters.max_num_of_operator_attempts):
При текущем значении `max_num_of_operator_attempts` в 100 и неудачной мутации (например, удаление узла из графа с одним узлом), будет чрезмерное и бессмысленное зацикливание.

2023-11-08 11:44 UTC, kasyanovse commented on golem/core/optimisers/genetic/operators/mutation.py
> +                break
Это можно перенести в `_sample_num_of_mutations`.

2023-11-08 11:44 UTC, kasyanovse commented on golem/core/optimisers/genetic/operators/mutation.py
> +                                  parameters=self.parameters)
Может быть перенести это в цикл в `_apply_mutations`? Зачем отдельный метод на 2 строки, применяемый 1 раз?

2023-11-08 11:44 UTC, kasyanovse commented on golem/core/optimisers/genetic/operators/mutation.py
> +    def _get_mutation_func(self, mutation_type: MutationIdType) -> Callable:
Почему `MutationIdType`, а не то, что было?

2023-11-08 11:44 UTC, kasyanovse commented on test/integration/test_genetic_schemes.py
> +    assert history.generations_count >= num_iterations // 3 * 1.2 + 2
Почему количество поколений может быть меньше, чем количество итераций? Потому что можно найти нужный граф быстрее?

2023-12-04 13:27 UTC, YamLyubov commented on golem/core/optimisers/genetic/operators/mutation.py
> +                                  parameters=self.parameters)
[Done](https://github.com/aimclub/GOLEM/pull/238/files#diff-826b69838a90fd12b907963e850a715b0af99484452f4430ef5d9913151e31c2R134)

2023-12-08 10:14 UTC, MorrisNein commented on golem/core/optimisers/genetic/operators/mutation.py
> +        graph = deepcopy(individual.graph)
Подскажи, а зачем тут deepcopy? Какая-то из проверок может модифицировать граф?

2023-12-08 11:37 UTC, YamLyubov commented on golem/core/optimisers/genetic/operators/mutation.py
> +        graph = deepcopy(individual.graph)
Этот deepcopy кажется теперь и не нужен

2023-12-08 12:20 UTC, YamLyubov commented on golem/core/optimisers/genetic/operators/mutation.py
> +                if is_correct_graph and graph != new_graph:
Переписала мутации так, чтобы они до последнего пытались сделать изменеие и убрала эту проверку на равенство.

2023-12-08 12:20 UTC, YamLyubov commented on golem/core/optimisers/genetic/operators/mutation.py
> +            for _ in range(self.parameters.max_num_of_operator_attempts):
Не уверена, стоит ли умееньшать это число повторений - пока оставила

2023-12-08 12:51 UTC, kasyanovse approved these changes

2023-12-21 11:10 UTC, kasyanovse commented
В [строке](https://github.com/aimclub/GOLEM/blob/533ab80814781252aa7f4def75b48fc5987022ec/golem/core/optimisers/genetic/gp_optimizer.py#L91) происходит проверка `verifier`ом сразу после мутации. По идее, эта проверка реализована внутри мутации, ее можно убрать.

2023-12-26 13:32 UTC, kasyanovse commented
У меня почему-то в `ParentOperator` в `operators` лежат функции, что несериализуемо и неудобно. Может быть хранить там строки, как сделано в кроссовере?
Я могу залить оба изменения, которые предложил в последних комментах.

2023-12-27 11:21 UTC, merged