Fix sequential
aimclub/GOLEM pull request #248
Opened 2023-12-08 12:41 UTC by YamLyubov

WIP

2023-12-08 12:41 UTC, pep8speaks commented
Hello @YamLyubov! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`golem/core/tuning/hyperopt_tuner.py`](https://github.com/aimclub/GOLEM/blob/5d0e59a267f09f2109968e20d28b2116d2de4147/golem/core/tuning/hyperopt_tuner.py):

> [Line 3:1](https://github.com/aimclub/GOLEM/blob/5d0e59a267f09f2109968e20d28b2116d2de4147/golem/core/tuning/hyperopt_tuner.py#L3): [F401](https://duckduckgo.com/?q=pep8%20F401) 'functools.partial' imported but unused
> [Line 14:1](https://github.com/aimclub/GOLEM/blob/5d0e59a267f09f2109968e20d28b2116d2de4147/golem/core/tuning/hyperopt_tuner.py#L14): [F401](https://duckduckgo.com/?q=pep8%20F401) 'golem.core.optimisers.graph.OptGraph' imported but unused

* In the file [`golem/core/tuning/sequential.py`](https://github.com/aimclub/GOLEM/blob/5d0e59a267f09f2109968e20d28b2116d2de4147/golem/core/tuning/sequential.py):

> [Line 4:1](https://github.com/aimclub/GOLEM/blob/5d0e59a267f09f2109968e20d28b2116d2de4147/golem/core/tuning/sequential.py#L4): [F401](https://duckduckgo.com/?q=pep8%20F401) 'typing.Tuple' imported but unused
> [Line 213:13](https://github.com/aimclub/GOLEM/blob/5d0e59a267f09f2109968e20d28b2116d2de4147/golem/core/tuning/sequential.py#L213): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable 'parameters_dict' is assigned to but never used

* In the file [`golem/core/tuning/simultaneous.py`](https://github.com/aimclub/GOLEM/blob/5d0e59a267f09f2109968e20d28b2116d2de4147/golem/core/tuning/simultaneous.py):

> [Line 38:121](https://github.com/aimclub/GOLEM/blob/5d0e59a267f09f2109968e20d28b2116d2de4147/golem/core/tuning/simultaneous.py#L38): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (128 > 120 characters)
> [Line 88:13](https://github.com/aimclub/GOLEM/blob/5d0e59a267f09f2109968e20d28b2116d2de4147/golem/core/tuning/simultaneous.py#L88): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable 'operation_name' is assigned to but never used

2023-12-18 07:49 UTC, kasyanovse requested changes

2023-12-18 07:49 UTC, kasyanovse commented on golem/core/tuning/hyperopt_tuner.py
> +        This allows not to lose results obtained while composition process
Справка запутала или я туплю. Поиск на фиксированных параметрах?

2023-12-18 07:49 UTC, kasyanovse commented on golem/core/tuning/hyperopt_tuner.py
> +        try_initial_parameters = initial_parameters and self.iterations > 1
Если подразумевается что `initial_parameters` может быть пустым, то может быть задать его по умолчанию `None`?

2023-12-18 07:49 UTC, kasyanovse commented on golem/core/tuning/hyperopt_tuner.py
> +        is_init_params_full = len(initial_parameters) == len(search_space)
А может быть такое, что длины будут равны, но ключи не будут совпадать?

2023-12-18 07:49 UTC, kasyanovse commented on golem/core/tuning/hyperopt_tuner.py
> +        if self.iterations < 10 or is_init_params_full:
Почему если заданы все параметры, то всего 1 итерация поиска? Обычно наоборот, чем больше параметров, тем больше нужно итераций.

2023-12-18 07:49 UTC, kasyanovse commented on golem/core/tuning/hyperopt_tuner.py
> +    operation_name = node.name
Это точно так? В `FEDOT` `name` и `operation_type` не обязательно должны совпадать. Может быть безопаснее взять `opearation_name` непосредственно из `operation`?

2023-12-18 07:49 UTC, kasyanovse commented on golem/core/tuning/sequential.py
> +                 timeout=seconds_per_node)
А куда результат записывается?

2023-12-18 07:49 UTC, kasyanovse commented on golem/core/tuning/sequential.py
>      def _optimize_node(self, graph: OptGraph,
А зачем здесь нужна оптимизация с начальных параметров?

2024-02-13 14:30 UTC, YamLyubov commented on golem/core/tuning/hyperopt_tuner.py
> +        This allows not to lose results obtained while composition process
Имеется в виду, что мы фиксируем часть параметров, которые были заданы изначально, и варьируем остальные параметры

2024-02-13 14:34 UTC, YamLyubov commented on golem/core/tuning/hyperopt_tuner.py
> +        is_init_params_full = len(initial_parameters) == len(search_space)
Нет, не может, так как ключи initial_parameters это всегда подмножество ключей search_space. [Здесь](https://github.com/aimclub/GOLEM/pull/248/files/2f9c085ae09f5b513b43635f62ec69ca494bac9c#diff-b1ee115be952cf2e5f9a343403c5b395a6a997f07513a8629374063fe68e185eR151-R165) это можно увидеть.

2024-02-13 14:44 UTC, YamLyubov commented on golem/core/tuning/hyperopt_tuner.py
> +        if self.iterations < 10 or is_init_params_full:
Если заданы все параметры, то мы хотим просто добавить в историю оптимизации эту точку в пространстве - поэтому только одна итерация.

В целом стоит учитывать следующее - у вершины не всегда заданы все возможные параметры, а так же могут быть заданы такие параметры, которых нет в соответствующем пространстве поиска. То есть, например, пусть у нас вершина типа 'cat' с параметрами color='gray', age=4. Но search space может быть таким color =['gray', 'red', 'whight', 'black'], hair=['long', 'short', 'no'].

Поэтому у нас при search_near_initial_parameters будет зафиксирован параметр color='gray', а по параметру hair будет проводиться поиск. Если бы у нас была вершина 'cat' с параметрами color='gray', age=4, hair='short', то при search_near_initial_parameters у нас будут зафиксированы все параметры из пространства поиска и варьировать уже будет нечего.

2024-02-13 14:47 UTC, YamLyubov commented on golem/core/tuning/sequential.py
>      def _optimize_node(self, graph: OptGraph,
Она нужна, чтобы не возник случай, когда у нас с начальными параметрами метрика была 1.25, но во время поиска эта точка не была рассмотрена и алгоритм возвращает 1.27 (хуже). Мы хотим дать алгоритму дополнительную инфу как бы

2024-02-13 14:47 UTC, YamLyubov commented on golem/core/tuning/sequential.py
> +                 timeout=seconds_per_node)
Он записывается в trials

2024-02-13 14:54 UTC, YamLyubov commented on golem/core/tuning/hyperopt_tuner.py
> +    operation_name = node.name
Из кода PipelineNode как раз получается, что name соответствует operation_type
![image](https://github.com/aimclub/GOLEM/assets/43475193/d7ee9908-1a0f-4275-91f5-5dd94c60c46a)

2024-02-13 15:10 UTC, YamLyubov commented on golem/core/tuning/hyperopt_tuner.py
> +        try_initial_parameters = initial_parameters and self.iterations > 1
Готово

2024-02-21 18:40 UTC, kasyanovse approved these changes

2024-06-04 14:38 UTC, merged