Add custom selection
aimclub/GOLEM pull request #249
Opened 2023-12-08 14:59 UTC by YamLyubov

Now useres can set custom selection function of type `custom_selection(populattion: PopulationT, pop_size: int]) -> PopulationT`

2023-12-18 07:21 UTC, kasyanovse requested changes

2023-12-18 07:21 UTC, kasyanovse commented on golem/core/optimisers/genetic/gp_params.py
> +    selection_types: Sequence[Union[SelectionTypesEnum, Any]] = None
Здесь тип `selection_types` указан как `Any`, а в `selection.py` идет проверка на `Callable`.
Не нужно ли указывать `Optional` если аргумент по умолчанию `None`?

2023-12-19 13:03 UTC, maypink approved these changes

2024-02-13 14:26 UTC, YamLyubov commented on golem/core/optimisers/genetic/gp_params.py
> +    selection_types: Sequence[Union[SelectionTypesEnum, Any]] = None
Готово

2024-02-13 14:40 UTC, kasyanovse approved these changes

2024-02-14 11:21 UTC, merged