Fix hyperopt randint
aimclub/GOLEM pull request #250
Opened 2023-12-09 09:04 UTC by MorrisNein

Monkey-patch the `hyperopt.hp.randint` near the definition of `HyperoptTuner`.

Makes it return an `int` instead of a `np.int64`.

2023-12-09 09:08 UTC, pep8speaks commented
Hello @MorrisNein! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`test/unit/tuning/test_tuning.py`](https://github.com/aimclub/GOLEM/blob/8d5a7bda76c556d4fd742a6448c6781361c26bd9/test/unit/tuning/test_tuning.py):

> [Line 43:21](https://github.com/aimclub/GOLEM/blob/8d5a7bda76c556d4fd742a6448c6781361c26bd9/test/unit/tuning/test_tuning.py#L43): [E202](https://duckduckgo.com/?q=pep8%20E202) whitespace before '}'

2023-12-12 13:45 UTC, kasyanovse requested changes

2023-12-12 13:45 UTC, kasyanovse commented on test/unit/tuning/test_tuning.py
> +                                               f'Got "{type(val)}".')
```suggestion
            assert val.__class__.__module__ != 'numpy', (f'The parameter "{param}" should not be a numpy type. '
                                               f'Got "{type(val)}".')
```

2023-12-12 13:45 UTC, kasyanovse commented on golem/core/tuning/hyperopt_tuner.py
> +    return scope.int(scope.hyperopt_param(label, scope.randint(*args, **kwargs)))
Наверное, стоит так же обернуть `float`.
Тогда можно будет фикс [убрать](https://github.com/aimclub/FEDOT/blob/c38c22f7d5f36d9f5b544bd078a9726f1a8c822a/fedot/core/pipelines/tuning/hyperparams.py#L89).

2023-12-12 14:19 UTC, MorrisNein commented on golem/core/tuning/hyperopt_tuner.py
> +    return scope.int(scope.hyperopt_param(label, scope.randint(*args, **kwargs)))
Не совсем понял, что ещё оборачивать

2023-12-12 14:26 UTC, kasyanovse commented on golem/core/tuning/hyperopt_tuner.py
> +    return scope.int(scope.hyperopt_param(label, scope.randint(*args, **kwargs)))
Что-то вроде:

```
def hp_normal(label, *args, **kwargs):
    return scope.float(scope.hyperopt_param(label, scope.normal(*args, **kwargs)))
```

```
def hp_uniform(label, *args, **kwargs):
    return scope.float(scope.hyperopt_param(label, scope.uniform(*args, **kwargs)))
```

И для `sample` (но здесь без учета размера возвращаемого значения).

```
def hp_sample(label, *args, **kwargs):
    return scope.float(scope.hyperopt_param(label, scope.sample(*args, **kwargs)))
```

У меня был аналогичный баг с `float` когда-то.

2023-12-12 14:32 UTC, MorrisNein commented on golem/core/tuning/hyperopt_tuner.py
> +    return scope.int(scope.hyperopt_param(label, scope.randint(*args, **kwargs)))
А это и так обёрнуто в hyperopt. Они только в randint забыли

2023-12-12 14:49 UTC, kasyanovse commented on golem/core/tuning/hyperopt_tuner.py
> +    return scope.int(scope.hyperopt_param(label, scope.randint(*args, **kwargs)))
Хотя не ясно как. Я дам approve, но если будут идеи как это сделать, то можно и в этом PR обернуть.

2023-12-12 14:49 UTC, kasyanovse approved these changes

2023-12-12 15:00 UTC, MorrisNein commented on golem/core/tuning/hyperopt_tuner.py
> +    return scope.int(scope.hyperopt_param(label, scope.randint(*args, **kwargs)))
> `hp_sample`

Не нашёл такую функцию

2023-12-12 15:02 UTC, MorrisNein commented on golem/core/tuning/hyperopt_tuner.py
> +    return scope.int(scope.hyperopt_param(label, scope.randint(*args, **kwargs)))
> А, точно, не заметил) Ты планируешь сделать PR в https://github.com/hyperopt/hyperopt?

Агась. Уже сделал.

2023-12-12 16:18 UTC, merged