Fix adding mutation as parent operator
aimclub/GOLEM pull request #262
Opened 2024-01-29 16:18 UTC by YamLyubov

- Mutation should be saved as a string to avoid problems with custom mutations serialisation
- Bandits should store arm action mapping accordingly: key should be a string

2024-01-29 16:18 UTC, pep8speaks commented
Hello @YamLyubov! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`examples/molecule_search/experiment.py`](https://github.com/aimclub/GOLEM/blob/03c49d181ee2566dbb69068388e78a448a905761/examples/molecule_search/experiment.py):

> [Line 30:1](https://github.com/aimclub/GOLEM/blob/03c49d181ee2566dbb69068388e78a448a905761/examples/molecule_search/experiment.py#L30): [F401](https://duckduckgo.com/?q=pep8%20F401) 'golem.core.paths.project_root' imported but unused

2024-01-31 17:14 UTC, kasyanovse requested changes

2024-01-31 17:14 UTC, kasyanovse commented on examples/molecule_search/experiment.py
> +                   # pretrain_dir=os.path.join(project_root(), 'examples', 'molecule_search', 'histories')
Это случайно попало или так и задумано?

2024-01-31 17:14 UTC, kasyanovse commented on golem/core/optimisers/adaptive/mab_agents/mab_agent.py
> +        self._arm_by_action = dict(map(lambda x, y: (str(x), y), actions, self._indices))
Преобразование `str(fun)`, если не ошибаюсь, в разных потоках для одной функции даст разные результаты. Если бандит будет работать в разных потоках (что возможно в будущем?), то это место для потенциальной ошибки.
Можно перебдеть и везде использовать `__name__` и `name`. Проще всего сделат маппинг `__name__` на `name` для `Enum` с типами мутаций.

2024-01-31 17:14 UTC, kasyanovse commented on golem/core/optimisers/adaptive/mab_agents/mab_agent.py
> +        self._arm_by_action = dict(map(lambda x, y: (str(x), y), actions, self._indices))
Хотя, в целом, дело даже не в бандитах. Если индивиды будут готовиться в разных потоках (что будет, надеюсь, в ближайшем будущем), то при использовании `str` одна и та же функция мутации даст разные строки в разных потоках, что некорректно.

2024-02-13 15:35 UTC, YamLyubov commented on examples/molecule_search/experiment.py
> +                   # pretrain_dir=os.path.join(project_root(), 'examples', 'molecule_search', 'histories')
Исправила

2024-02-13 15:36 UTC, YamLyubov commented on golem/core/optimisers/adaptive/mab_agents/mab_agent.py
> +        self._arm_by_action = dict(map(lambda x, y: (str(x), y), actions, self._indices))
Это тоже поправила

2024-02-14 18:32 UTC, kasyanovse commented on golem/core/optimisers/adaptive/mab_agents/mab_agent.py
> +        self._arm_by_action = dict(map(lambda x, y: (str(x), y), actions, self._indices))
Можно поступить не очень изящно: создать класс `CustomMutation` и оборачивать в него все кастомные мутации. Или динамически создавать `Enum` с мутациями, тогда у каждой мутации будет `name`.

2024-06-07 10:54 UTC, kasyanovse approved these changes

2024-06-07 11:24 UTC, merged