Add tuning docs
aimclub/GOLEM pull request #46
Opened 2023-02-22 08:35 UTC by YamLyubov

WIP

2023-02-28 10:03 UTC, gkirgizov requested changes

2023-02-28 10:03 UTC, gkirgizov commented on docs/source/api/tuning.rst
> +To specify parameters search space use ``SearchSpace`` class.
Добавь, пожалуйста, минимальный пример спецификации либо ссылку на код, где такой пример есть

2023-03-03 11:42 UTC, YamLyubov commented on docs/source/api/tuning.rst
> +To specify parameters search space use ``SearchSpace`` class.
Добавила: https://thegolem--46.org.readthedocs.build/en/46/api/tuning.html

2023-03-03 12:45 UTC, gkirgizov commented on docs/source/api/tuning.rst
> +To specify parameters search space use ``SearchSpace`` class.
добави только кодовые кавычки для  {‘operation_name’: {‘param_name’: (hyperopt distribution function, [sampling scope]), …}, …}.

2023-03-03 13:07 UTC, YamLyubov commented on docs/source/api/tuning.rst
> +To specify parameters search space use ``SearchSpace`` class.
Готово

2023-03-06 09:19 UTC, gkirgizov approved these changes

2023-03-06 09:21 UTC, merged