implement SA
aimclub/GOLEM pull request #62
Opened 2023-03-06 12:58 UTC by maypink

WIP

2023-03-06 13:14 UTC, nicl-nno commented on golem/sensitivity_analysis/optimization_operations.py
> +    """ Get available operations for the task and exclude forbidden ones """
А это вообще нужно в GOLEM-е? Cклеивание довольно сложно представить для произвольных графов. Можно попробовать вынести как реализацию кроссовера.

2023-03-06 13:31 UTC, nicl-nno commented on golem/sensitivity_analysis/graph_labels_using_sa.py
> +    'EdgeReplaceOperationAnalyze': 'ER'
Вопрос - операция EdgeReplace из всех выглядит наименее атомарной. Не лучше ли её заменить на EdgeAdd?

2023-03-06 13:54 UTC, nicl-nno commented on golem/sensitivity_analysis/graph_labels_using_sa.py
> +def draw_nx_dag(graph: GraphType,
Может, это всё отвязать от SA и унести в визуализатор? Ведь может и для чего-то другого быть полезным показывать изменения и рисовать веса.

2023-03-06 21:11 UTC, nicl-nno commented on golem/sensitivity_analysis/optimization_operations.py
> +    """ Get available operations for the task and exclude forbidden ones """
Я понял, потому и накидал только самые высокоуровневые комменты)

2023-03-11 21:43 UTC, maypink commented
- [ ] implement optimize (unlink logic from initialization for every new graph, make it more general)
- [ ] fixes in optimization itself concerned with differences between pipeline and optgraph
- [ ] rebuild using of `analyse` method with new classes for result presenting
- [ ] present EdgeReplacement as EdgeDeletion + EdgeAddition
- [ ] visualizations (more likely new PR)

2023-03-14 13:49 UTC, maypink commented
при таком стартовом графе:
![image](https://user-images.githubusercontent.com/57305249/225022054-ad2c5594-d0e5-4e6c-8c26-682b8c4f15d3.png)
получаются такие варианты, каждая картинка -- оптимизированный с SA граф. оптимизация (метрика для нее) здесь игрушечная, но картинки прикольные.
![image](https://user-images.githubusercontent.com/57305249/225021997-1357ee4d-2b44-439d-be4a-c6471f0b58cc.png)

2023-03-14 14:11 UTC, maypink commented on golem/sensitivity_analysis/graph_labels_using_sa.py
> +    'EdgeReplaceOperationAnalyze': 'ER'
мне кажется, что для анализа графа достаточно удаления нод и ребер, а в плане просто использования во время эволюции или для докручивания графа в конце: 
1) если добавлять `EdgeAddition`, то в добавок к уже имеющемуся, а не вместо `EdgeReplacement`, тк `EdgeDeletion` + `EdgeAddition` != `EdgeReplacement`
2) и SA был про уменьшение/сжатие графа, а атомарное добавление чего-либо будто бы уже не его зона ответственности

2023-03-14 14:12 UTC, maypink commented on golem/sensitivity_analysis/graph_labels_using_sa.py
> +def draw_nx_dag(graph: GraphType,
я думаю, с визуализациями лучше перейти в следующий пр, а здесь построить каркас. пока удалила все файлы с ними связанные

2023-03-14 14:14 UTC, nicl-nno commented on golem/sensitivity_analysis/graph_labels_using_sa.py
> +def draw_nx_dag(graph: GraphType,
ок

2023-03-14 14:16 UTC, maypink commented on golem/sensitivity_analysis/optimization_operations.py
> +    """ Get available operations for the task and exclude forbidden ones """
угу, удалила в итоге пока что. а насчет кроссовера: здесь графы склеивались просто друг за дружкой, так что и правда сложно такое представить хоть для какой-то структуры

2023-03-20 14:59 UTC, maypink commented on examples/structural_analysis/opt_graph_optimization.py
> +    sa = GraphStructuralAnalysis(objectives=[objective] * 2, node_factory=node_factory,
а это чтобы показать, что можно считать несколько метрик. оптимизируется оно по выбранной с помощью `main_metric_idx` в `StructuralAnalysisRequirements`

2023-03-20 15:34 UTC, nicl-nno commented on examples/structural_analysis/opt_graph_optimization.py
> +    sa = GraphStructuralAnalysis(objectives=[objective] * 2, node_factory=node_factory,
Ну лучше в примере показать более реальный вариант, создав вторую функцию для доп. метрики.

2023-03-21 01:19 UTC, gkirgizov commented on examples/structural_analysis/opt_graph_optimization.py
> +    sa = GraphStructuralAnalysis(objectives=[objective] * 2, node_factory=node_factory,
Вообще говоря, Objective уже может нести в себе несколько метрик качества и сложности. Оправдано ли еще делать неколько Objective?

2023-03-21 02:29 UTC, gkirgizov requested changes

2023-03-21 02:29 UTC, gkirgizov commented on golem/structural_analysis/graph_sa/edges_analysis.py
> +    def analyze(self, graph: OptGraph, results: SAAnalysisResults = None,
Лучше поменяй `OptGraph` в сигнатурах на  `Graph`. OptGraph -- это скорее синоним для конкретного подкласса Graph, полезен только для создания графов. А так все классы могут работать с интерфейсом Graph

2023-03-21 02:29 UTC, gkirgizov commented on golem/structural_analysis/graph_sa/result_presenting_structures/object_sa_result.py
> +                return method
Кажется, этот класс ниже в своем файле продублирован

2023-03-21 10:23 UTC, maypink commented on examples/structural_analysis/opt_graph_optimization.py
> +    sa = GraphStructuralAnalysis(objectives=[objective] * 2, node_factory=node_factory,
ну с такой objective, конечно, вообще здорово работается:) , [done](https://github.com/aimclub/GOLEM/pull/62/commits/a83742727c3d5a1431d7ff55b76d5eb450f6e52f)

2023-03-21 11:57 UTC, maypink commented on golem/structural_analysis/graph_sa/edge_sa_approaches.py
> +                timer: OptimisationTimer = None) -> ObjectSAResult:
[done](https://github.com/aimclub/GOLEM/pull/62/commits/097a75bf399e180e72fac7e9102bcd6c0cf41fe7#diff-f5dc3c5f84fd9b1a02aa07a386fff5d6128dde061192b54b42fc54a7b17194aaR31)

2023-03-21 11:57 UTC, maypink commented on golem/structural_analysis/graph_sa/edges_analysis.py
> +    def analyze(self, graph: OptGraph, results: SAAnalysisResults = None,
[done](https://github.com/aimclub/GOLEM/pull/62/commits/097a75bf399e180e72fac7e9102bcd6c0cf41fe7#diff-f5dc3c5f84fd9b1a02aa07a386fff5d6128dde061192b54b42fc54a7b17194aaR31)

2023-03-23 06:48 UTC, gkirgizov requested changes
Я несколько раз запустил пример examples/structural_analysis/opt_graph_optimization.py , и из 5 раз он 3 раза повис на разных этапах. То ли дело в многопроцессорном режиме, то ли где-то еще подвисает, неочевидно. Посмотри, пожалуйста, в чем дело.

Еще такой Warning вылетает иногда `GOLEM/golem/structural_analysis/graph_sa/node_sa_approaches.py:126: RuntimeWarning: invalid value encountered in double_scalars
  res.append(self._origin_metrics[i] / modified_graph_metrics[i])`

2023-03-27 09:03 UTC, merged