Add IOpt tuner
aimclub/GOLEM pull request #70
Opened 2023-03-23 12:08 UTC by YamLyubov

WIP

2023-04-13 10:40 UTC, nicl-nno requested changes

2023-04-13 10:40 UTC, nicl-nno commented on golem/core/tuning/iopt_tuner.py
> +    def Calculate(self, point: Point, functionValue: FunctionValue) -> FunctionValue:
А почему не calculate?

2023-04-13 10:40 UTC, nicl-nno commented on golem/core/tuning/tuner_interface.py
> -                 timeout: timedelta = timedelta(minutes=5),
А может оставить эти параметры и в базовом тюнере? Конкретная реализация может их игнорировать, это уже её дело.

2023-04-13 10:40 UTC, nicl-nno commented on requirements.txt
> +iOpt
Можно версию зафиксировать, сейчас 0.1.6.

2023-04-13 10:40 UTC, nicl-nno commented on golem/core/tuning/search_space.py
> +    def get_node_parameters_for_hyperopt(self, node_id, operation_name):
А можешь эти методы вынести в конкретные модульи для hyperopt и iopt?

2023-04-17 07:15 UTC, gkirgizov commented
> IOpt does not support nested search space, which can be nessesary

Касательно вложенных параметров. В целом, можно реаизовать двухсторонний маппинг, который будет вложенные словари переводить в не-вложенные, как-то специально переименовывая параметры. В духе
1. Трансформируем вложенный в не-вложенный: {'p1': 25, 'p_nested': {'a': 2}} -> {'p1': 25, 'p_nested/a': 2}
2. Отдаем оптимизатору
3. Трансформируем обратно

2023-04-17 09:24 UTC, YamLyubov commented on golem/core/tuning/iopt_tuner.py
> +    def Calculate(self, point: Point, functionValue: FunctionValue) -> FunctionValue:
Данный метод - реализация абстрактного метода из класса `Problem` из IOpt. Поэтому переименовать его можно только там

2023-04-17 09:39 UTC, nicl-nno commented on golem/core/tuning/iopt_tuner.py
> +    def Calculate(self, point: Point, functionValue: FunctionValue) -> FunctionValue:
Ок. Ну в целом можно вкинуть коллегам PR с правкой)

2023-04-17 09:49 UTC, YamLyubov commented on golem/core/tuning/search_space.py
> +    def get_node_parameters_for_hyperopt(self, node_id, operation_name):
В конкретные модули - это в отдельные модули или в файлы, где лежат классы соответствующих тюнеров?

2023-04-17 10:07 UTC, gkirgizov requested changes

2023-04-17 10:07 UTC, gkirgizov commented on golem/core/tuning/tuner_interface.py
> +                 algo: Callable = None,
Optional (и адаптер)

2023-04-17 10:07 UTC, gkirgizov commented on test/unit/tuning/test_tuning.py
> +                'type': 'categorical'
Кстати, а что произойдет при параметре categorical в iOpt?
Ошибка выетет? Или как-то молча проскочит?

2023-04-17 10:37 UTC, YamLyubov commented on golem/core/tuning/iopt_tuner.py
> +        self.numberOfFloatVariables = len(self.floatVariableNames)
Да, верно

2023-04-18 09:41 UTC, YamLyubov commented on golem/core/tuning/tuner_interface.py
> -                 timeout: timedelta = timedelta(minutes=5),
[Вернула ](https://github.com/aimclub/GOLEM/pull/70/files#diff-1f87812e47ef7b23a646340370b8f700524fb1ac518fce5804e47cd5929b0211R41-R46)

2023-04-18 09:41 UTC, YamLyubov commented on requirements.txt
> +iOpt
[Добавила](https://github.com/aimclub/GOLEM/pull/70/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R25)

2023-04-18 09:43 UTC, YamLyubov commented on golem/core/tuning/search_space.py
> +    def get_node_parameters_for_hyperopt(self, node_id, operation_name):
[Тут](https://github.com/aimclub/GOLEM/pull/70/files#diff-1f87812e47ef7b23a646340370b8f700524fb1ac518fce5804e47cd5929b0211R248) и [тут](https://github.com/aimclub/GOLEM/pull/70/files#diff-be29689607e6f62fd4cb9e1d70b9591b85b2afbde3f1558461c7ca1e6a1bd739R227) расположила

2023-04-18 09:44 UTC, YamLyubov commented on golem/core/tuning/iopt_tuner.py
> +        new_parameters = get_parameters_dict_from_iopt_point(point, self.floatVariableNames, self.discreteVariableNames)
[ Сделала](https://github.com/aimclub/GOLEM/pull/70/files#diff-be29689607e6f62fd4cb9e1d70b9591b85b2afbde3f1558461c7ca1e6a1bd739R84)

2023-04-18 09:46 UTC, YamLyubov commented on golem/core/tuning/iopt_tuner.py
> +    def __init__(self, objective_evaluate: ObjectiveEvaluate,
[Done](https://github.com/aimclub/GOLEM/pull/70/files#diff-1f87812e47ef7b23a646340370b8f700524fb1ac518fce5804e47cd5929b0211R41)

2023-04-18 09:47 UTC, YamLyubov commented on golem/core/tuning/search_space.py
> +            'type': 'discrete'}, ...}, ..}
[Done](https://github.com/aimclub/GOLEM/pull/70/files#diff-479b583d77e0bdc1448734ca7241a3093b42442f2c6a8a2ad5aaf1b96945c4b1R9)

2023-04-18 09:47 UTC, YamLyubov commented on golem/core/tuning/search_space.py
> +    def __init__(self, search_space: Dict[str, Dict[str, Dict[str, Union[Callable, List, str]]]]):
[Done](https://github.com/aimclub/GOLEM/pull/70/files#diff-479b583d77e0bdc1448734ca7241a3093b42442f2c6a8a2ad5aaf1b96945c4b1R3)

2023-04-18 09:48 UTC, YamLyubov commented on test/unit/tuning/test_tuning.py
> +                'type': 'categorical'
Проскочит молча - просто этот параметр будет игнорироваться

2023-04-19 05:58 UTC, gkirgizov requested changes

2023-04-19 05:58 UTC, gkirgizov commented on golem/core/tuning/iopt_tuner.py
> +                                            discrete_parameters_names: List[str]) -> Dict[str, Any]:
Так, кажется, эти параметры передавать не нужно, тк они в self

2023-04-19 05:58 UTC, gkirgizov commented on golem/core/tuning/tuner_interface.py
> +class HyperoptTuner(BaseTuner, ABC):
Раз у нас есть файл с базовым интерфейсом Тюнера, то реализации (в тч HyperoptTuner) стоит вынести в свои файлы/модули. 

Так название файла (tuner_interface) будет отвечать его цели. Также, IOptTuner при импорте базового класса буде впустую импортировать hyperopt. Вот всяких подобных штуки и плюс слуайных циклических зависимостей и тд позволяет избжеать четкое раздаление на модули.

2023-04-24 12:16 UTC, YamLyubov commented on golem/core/tuning/iopt_tuner.py
> +                                            discrete_parameters_names: List[str]) -> Dict[str, Any]:
[Done ](https://github.com/aimclub/GOLEM/pull/70/files#diff-be29689607e6f62fd4cb9e1d70b9591b85b2afbde3f1558461c7ca1e6a1bd739R81)

2023-04-24 13:15 UTC, nicl-nno approved these changes

2023-04-25 03:54 UTC, gkirgizov approved these changes

2023-05-30 09:57 UTC, merged