labels visualization
aimclub/GOLEM pull request #76
Opened 2023-04-04 14:50 UTC by maypink

WIP

2023-04-04 14:55 UTC, maypink commented
конкретно SA подвяжу, как[ этот пр](https://github.com/aimclub/GOLEM/pull/73) закроется

2023-04-04 16:51 UTC, MorrisNein commented on golem/core/dag/graph.py
> +            .visualise(save_path, engine, node_color, dpi, node_size_scale, font_size_scale, edge_curvature_scale)
Подскажи, зачем прокидываешь через visuals_params?
Это временное решение или так планируешь оставить?

Просто смысл этого параметра в хранении дефолтных значений, всё заданное пользователем обычно передаётся через visualise

2023-04-10 10:17 UTC, maypink commented on golem/core/dag/graph.py
> +            .visualise(save_path, engine, node_color, dpi, node_size_scale, font_size_scale, edge_curvature_scale)
ага, окей, [поменяла](https://github.com/aimclub/GOLEM/pull/76/commits/cd7691ebe68cafc900e49ce63e4b1e44ff578f77)

2023-04-10 15:43 UTC, maypink commented
С SA:
![image](https://user-images.githubusercontent.com/57305249/230937273-6d372079-f65e-46a0-bc99-2c6e9641e526.png)

2023-04-11 07:53 UTC, gkirgizov requested changes

2023-04-11 07:53 UTC, gkirgizov commented on golem/core/dag/verification_rules.py
> +    if isinstance(graph.root_node, Sequence) and len(graph.root_node) == 1 or not isinstance(graph.root_node, Sequence):
Предлагаю сделать отдельное правило на единственный корень и оставить на существование корней в целом

2023-04-11 07:53 UTC, gkirgizov commented on golem/structural_analysis/graph_sa/graph_structural_analysis.py
> +        self._log = default_log(prefix='SA')
SA -- не очевидно )

2023-04-11 10:00 UTC, maypink commented on golem/core/dag/verification_rules.py
> +    if isinstance(graph.root_node, Sequence) and len(graph.root_node) == 1 or not isinstance(graph.root_node, Sequence):
а, соре, я чет экспериментировала и забыла убрать, [поправила](https://github.com/aimclub/GOLEM/pull/76/files#diff-43a29112460ed2960916d42cf028ec4b7f701bf5379f2159556d9bf2460aba70R19)

2023-04-11 10:03 UTC, maypink commented on golem/structural_analysis/graph_sa/graph_structural_analysis.py
> +        self._log = default_log(prefix='SA')
[done](https://github.com/aimclub/GOLEM/pull/76/files#diff-c8749fb9b9e68e52402dd5fb3b5087ee4c84f7c8a2d73b0b18e2070d4973c0f3R48)

2023-04-14 11:07 UTC, nicl-nno commented on golem/structural_analysis/graph_sa/results/sa_analysis_results.py
> +        edges_results = self.results_per_iteration[str(iter)]['edge']
А почему нужно приведение к str? И нужен ли тут вообще словарь, если номера итераций вроде бы последовательны?

2023-04-14 11:09 UTC, nicl-nno commented on golem/structural_analysis/graph_sa/results/sa_analysis_results.py
> +        if results[0].entity_type == 'edge':
Не фанат енумов, но может тут они нужны? А то непонятно, какие entity_type бывают. Если только edge/node - то код можно упросить.

2023-04-17 08:39 UTC, maypink commented on golem/structural_analysis/graph_sa/results/sa_analysis_results.py
> +        edges_results = self.results_per_iteration[str(iter)]['edge']
к `str` приведение и правда не нужно, а насчет словаря: с ним просто удобнее работать. ну и кажется хранение при этом 'лишних' номеров итераций  -- не очень тяжелая штука

2023-04-17 08:40 UTC, maypink commented on golem/structural_analysis/graph_sa/results/sa_analysis_results.py
> +        if results[0].entity_type == 'edge':
ага, [добавила](https://github.com/aimclub/GOLEM/pull/76/commits/cd7e9b6489b69ebb9661907d951f74dbfec2eb02#diff-b38d130349de4afa08bc3320ec26a4394dc98ee443f3d3acaefa59d7c7f77781R8)

2023-04-17 10:09 UTC, gkirgizov approved these changes

2023-04-17 11:11 UTC, MorrisNein commented
Планируешь поддержку скруглённых рёбер в этом PR?

2023-04-17 13:42 UTC, maypink commented
> Планируешь поддержку скруглённых рёбер в этом PR?

да нет, честно говоря) пойду заведу ишую))

2023-04-17 15:38 UTC, merged