Add infrastructure for Adaptive Mutation agent & simple experiments
aimclub/GOLEM pull request #78
Opened 2023-04-05 07:28 UTC by gkirgizov

New logic:
- Adds new classes `OperatorAgent` and `ExperienceBuffer` for learning adaptive mutations
- Modifies `Mutation` operator to use new OperatorAgent, modifies `EvoGraphOptimizer` to collect and pass learning experience
- Adds new parameter to `GPAlgorithmParameters: adaptive_mutation_type`

New in examples:
- Refactors current structure of examples for experiments
- Adds simple experiments (like achieving graphs of certain size) that show some effectiveness of adaptive mutations (such task converges faster)

Resolves #41 (like a first prototype)
Contributes to #42

Any feedback very welcome

2023-04-07 21:34 UTC, nicl-nno commented on golem/core/optimisers/adaptive/operatoragent.py
> +import random
Для единообразия можно в названии добавить _

2023-04-07 21:35 UTC, nicl-nno commented on golem/core/optimisers/adaptive/operatoragent.py
> +    default = 'random'
Думаешь стоит дефолтное поведение определять как random прямо в enum-e?

2023-04-07 21:37 UTC, nicl-nno commented on golem/core/optimisers/adaptive/operatoragent.py
> +    def log_results(self, results: Sequence[Individual]):
Может вместо log использовать add/incorporate/consider?

А то путаница с логгером возникает.

2023-04-07 21:41 UTC, nicl-nno commented on golem/core/optimisers/adaptive/operatoragent.py
> +        self.log_experience(obs.graph, action, reward=-1.0)
А это точно нужно в виде отдельного метода? Учитывая, что action можно вытащить из Individual, судя по коду выше.

2023-04-07 21:42 UTC, nicl-nno commented on golem/core/optimisers/adaptive/operatoragent.py
> +    def log_experience(self, obs: ObsType, action: ActType, reward: float):
Для понятности стоит расставить метки приватных методов.

2023-04-07 21:43 UTC, nicl-nno commented on golem/core/optimisers/adaptive/operatoragent.py
> +        self.log_experience(obs.graph, action, reward=-1.0)
Ещё путает что где-то obs это Individual, а где-то ObsType (== Graph)

2023-04-07 21:46 UTC, nicl-nno commented on golem/core/optimisers/genetic/gp_params.py
> +    :param variable_mutation_num: determines if in each syle mutations applies once or possibly few times
syle?

2023-04-07 21:50 UTC, nicl-nno commented on golem/core/optimisers/genetic/operators/mutation.py
> +        # most of the time returns 1 or rarely several mutations
А это точно хорошо? Смысл нескольких последовательных мутаций в рамках одного применения собственно оператора был в том, что промежуточные состояния могут быть некорректными - это требования предъявляются только к финальному.

2023-04-07 21:52 UTC, nicl-nno commented on golem/core/optimisers/adaptive/operatoragent.py
> +    def _dbg_log(self, actions, rewards):
Выглядит очень похоже на аналогичный метод выше. Может в нем вызвать этот, из базового класса?

2023-04-07 22:00 UTC, nicl-nno commented on golem/core/optimisers/adaptive/mab_agent.py
> +class MultiArmedBanditAgent(OperatorAgent):
Здорово что получилось так струкурировать.

Было бы интересно посмотреть на реализацию MLAgent)

2023-04-07 22:01 UTC, nicl-nno commented on golem/core/optimisers/adaptive/mab_agent.py
> +    def partial_fit(self, experience: ExperienceBuffer):
А почему fit - partial?

2023-04-07 23:19 UTC, nicl-nno commented
Не в этом PR-е, но в будущем: было бы полезно реализовать подгрузку пред-обученного агента (и, соответственно, его сохранение). Чтобы он стартовал с какого-то warm start-а.

2023-04-10 08:43 UTC, maypink requested changes

2023-04-11 08:18 UTC, gkirgizov commented on golem/core/optimisers/adaptive/operatoragent.py
> +    default = 'random'
поправил

2023-04-11 08:36 UTC, gkirgizov commented on golem/core/optimisers/adaptive/operatoragent.py
> +        self.log_experience(obs.graph, action, reward=-1.0)
> Учитывая, что action можно вытащить из Individual, судя по коду выше.

Убрал метод в пользу использования `collect_experience`.

А вот  action записывается в Individual только при успешной мутации. Так что нужно отдельно указывать action & reward.

2023-04-11 08:37 UTC, gkirgizov commented on golem/core/optimisers/adaptive/operatoragent.py
> +    def log_experience(self, obs: ObsType, action: ActType, reward: float):
upd они теперь все публичные

2023-04-11 08:44 UTC, gkirgizov commented on golem/core/optimisers/adaptive/operatoragent.py
> +    def _dbg_log(self, actions, rewards):
Не очень понял мысль. В общем случае probability & action value неравны, это в случае RandomAgent action_value как таковых нет, поэтому возвращаются просто вероятности.

2023-04-11 08:45 UTC, gkirgizov commented on golem/core/optimisers/adaptive/mab_agent.py
> +class MultiArmedBanditAgent(OperatorAgent):
Reinforcement Learning то?) Да, его позапускать поинтереснее будет

2023-04-11 08:48 UTC, gkirgizov commented on golem/core/optimisers/adaptive/mab_agent.py
> +    def partial_fit(self, experience: ExperienceBuffer):
Потому что это online learning с непрерывным до-обучением. Fit скорее восприминается как обучение с нуля. 
Тут я следовал неймингу бэкэнд-библиотеки mabwiser, где бандиты у них имеют метод `partial_fit` & `fit`.

2023-04-11 08:52 UTC, gkirgizov commented
> Не в этом PR-е, но в будущем: было бы полезно реализовать подгрузку пред-обученного агента (и, соответственно, его сохранение). Чтобы он стартовал с какого-то warm start-а.

Завел issue

2023-04-11 08:58 UTC, gkirgizov commented on examples/synthetic_graph_evolution/graph_search.py
> +        objective = Objective(
добавил Exception, так точно ошибку нельзя пропустить

2023-04-11 09:10 UTC, gkirgizov commented on golem/core/optimisers/genetic/operators/mutation.py
> +        # most of the time returns 1 or rarely several mutations
Логика то, собственно, осталась прежней, я только вынес это количество мутаций в отдельную функцию.
А для текущих экспериментов я начал с самых простых постановок -- чтобы поведение оператора было предсказуемее, поэтому и добавил новую опцию `variable_mutation_num`. Когда стал смотреть -- выяснил, что и так чаще всего по 1 мутации применяется с таким сэмплированием, добавил коммент.

2023-04-11 13:57 UTC, nicl-nno commented on golem/core/optimisers/adaptive/operatoragent.py
> +    def _dbg_log(self, actions, rewards):
Я тут про _dbg_log.

2023-04-12 09:41 UTC, YamLyubov commented on golem/core/optimisers/genetic/operators/mutation.py
> +        mutation_applied = None
Здесь вроде можно не дублировать эту строчку из ```_apply_mutations```

2023-04-12 09:41 UTC, YamLyubov commented on golem/core/optimisers/genetic/operators/mutation.py
> +        if kind == MutationAgentTypeEnum.default or kind == MutationAgentTypeEnum.random:
Предполагается, что потом будет отдельная дефолтная реализация?

2023-04-12 09:41 UTC, YamLyubov commented on golem/core/optimisers/adaptive/mab_agent.py
> +                          n_jobs=1)
Может есть смысл сюда прокидывать ```n_jobs``` из ```GraphRequirements``` или это сильно не повлияет ни на что?

2023-04-12 09:41 UTC, YamLyubov commented on golem/core/optimisers/genetic/gp_params.py
> +    Requires crossover_types to be CrossoverTypesEnum.none for correct adaptive learning.
А я правильно поняла, что `CrossoverTypesEnum.none` нужно, чтобы мы точно знали, что полученное улучшение метрики произошло именно в результате мутации (а не кросовера)?

2023-04-13 17:05 UTC, maypink requested changes

2023-04-13 17:05 UTC, maypink commented on golem/core/optimisers/adaptive/operator_agent.py
> +        return actions, rewards
может лучше, чтобы observations он тоже возвращал? мне, например, для контекстуального пригодится

2023-04-18 06:09 UTC, gkirgizov commented on golem/core/optimisers/adaptive/mab_agent.py
> +class MultiArmedBanditAgent(OperatorAgent):
Понял, тут для начала нужно реализоовать https://github.com/aimclub/GOLEM/issues/77, чтобы пробовать различные SupervisedMLAgent, RLAgent. В процессе, словом

2023-04-18 06:39 UTC, gkirgizov commented on golem/core/optimisers/adaptive/operator_agent.py
> +        return actions, rewards
добавил

2023-04-18 06:39 UTC, gkirgizov commented on golem/core/optimisers/genetic/gp_params.py
> +    Requires crossover_types to be CrossoverTypesEnum.none for correct adaptive learning.
Да, все так

2023-04-18 06:45 UTC, gkirgizov commented on golem/core/optimisers/adaptive/mab_agent.py
> +                          n_jobs=1)
По крайней мере, медленее не стало, добавил

2023-04-18 06:47 UTC, gkirgizov commented on golem/core/optimisers/genetic/operators/mutation.py
> +        if kind == MutationAgentTypeEnum.default or kind == MutationAgentTypeEnum.random:
Это чтобы дефолтную реализацию можно было поменять

2023-04-18 06:48 UTC, gkirgizov commented on golem/core/optimisers/genetic/operators/mutation.py
> +        mutation_applied = None
Это нужно просто для объявления переменной, чтобы pcharm не ругался.

2023-04-18 06:49 UTC, gkirgizov commented on golem/core/optimisers/adaptive/operatoragent.py
> +    def _dbg_log(self, actions, rewards):
Убрал лишний код

2023-04-18 07:13 UTC, maypink approved these changes

2023-04-18 11:24 UTC, YamLyubov approved these changes

2023-04-24 07:30 UTC, nicl-nno approved these changes
Не забудь только поправить 

![image](https://user-images.githubusercontent.com/5711814/233928388-95ef4d1f-2399-41e9-9db6-00c16f3daf73.png)

2023-04-24 10:27 UTC, merged

2023-05-10 16:23 UTC, gkirgizov commented
Attaching first experiment results for quick reference:

Task: find graph of specified size; objective is difference to the target size

Bottom: GOLEM running without adaptive agent
Top: GOLEM running with MAB-agent with UCB policy
Left: fitness convergence by generation (x-axis)
Right: probabilities of mutations (y-axis) changing by generation (x-axis)

![compare_rand_ucb_](https://github.com/aimclub/GOLEM/assets/10994117/7adda3c3-7cf7-4def-a032-ce43d76b4166)