Add other optimizers
aimclub/GOLEM pull request #8
Opened 2022-12-16 14:59 UTC by YamLyubov

RandomSearchOptimizer and RandomMutationSearchOptimizer are added. 
BaseRandomOptGraphFactory is implemented to allow users to customise random graph generation.

2022-12-17 06:51 UTC, gkirgizov requested changes

2022-12-17 06:51 UTC, gkirgizov commented on examples/graph_model_optimization.py
> +            initial_graphs=initial)
Создание выглядит очень похожим -- может привести init к одному виду?

2022-12-17 06:51 UTC, gkirgizov commented on golem/core/optimisers/random/random_mutation_optimizer.py
> +            while not self.stop_optimization():
кажется, while в python не очень эффективен по сравнению с for циклом (тк while интерпретируется, а for-цикл исполняетс как сишный for), лучше изменить

2022-12-17 06:51 UTC, gkirgizov commented on golem/core/optimisers/random/random_mutation_optimizer.py
> +                mutation = Mutation(self.graph_optimizer_params, self.requirements, self.graph_generation_params)
может вынести это в init?

2022-12-17 06:51 UTC, gkirgizov commented on golem/core/optimisers/random/random_search.py
> +            while not self.stop_optimization():
то же самое с while / for

2022-12-17 06:51 UTC, gkirgizov commented on golem/core/optimisers/random/random_search.py
> +    def _init_assumption(self, evaluator: EvaluationOperator) -> Tuple[Fitness, Individual]:
предлагаю функции, обрабатывающие первую итерацию, назвать единообразно и дать им один интерфейс

2022-12-17 06:51 UTC, gkirgizov commented on golem/core/optimisers/random_graph_factory.py
> +        pass
Два предложения
- Раз это просто Callable -- давай заведем просто type alias, чтобы меньше сущностей вводить
- Назвать чуть попроще, а то взгляд спотыкается на тяжеловесном навзании. RandomGraphFactory, например

2022-12-17 06:51 UTC, gkirgizov commented on golem/core/optimisers/random_graph_factory.py
> +        graph_root = node_factory.get_node()
при создании Pipeline у нас что-нибудь ломается, если мы убираем `get_node(is_primary=True)` (или False)?

2022-12-17 06:51 UTC, gkirgizov commented on golem/core/optimisers/random_graph_factory.py
> +            if choices([0, 1], weights=[0.7, 0.3])[0]:
предлагаю вынести эту константу в аргумент с дефолтным значением

2022-12-17 06:51 UTC, gkirgizov commented on test/unit/optimizers/test_random_graph_factory.py
> +@pytest.mark.parametrize('max_depth', [1, 3, 5])
добавь еще значение побольше, 30 например

2022-12-17 06:51 UTC, gkirgizov commented on golem/core/optimisers/random_graph_factory.py
> +class DefaultRandomOptGraphFactory(BaseRandomOptGraphFactory):
Предлагю назвать более семантически -- например, RandomGrowthGraphFactory

2022-12-17 06:51 UTC, gkirgizov commented on test/unit/optimizers/test_random_graph_factory.py
> +        assert graph.depth <= requirements.max_depth
этот тест пройдетб если фабрика всегда будетт возвращать граф из единственной ноды )
можетб как-то проверять средний размер всех сгенерированных графов? он должен быть, скажем, больше половины макс гбины? или еще какой-то осмысленной нижней границы

2022-12-17 06:53 UTC, gkirgizov commented on golem/core/optimisers/random_graph_factory.py
> +class DefaultRandomOptGraphFactory(BaseRandomOptGraphFactory):
и стоит добавить доккоммент, мол, тут генерируем DAG с помощью случайного роста

2022-12-17 06:55 UTC, gkirgizov commented
@MorrisNein глянуь, пожалуйста, момент с добавлением в историю. надо ли там какие-то доп операции производить с отметкой natural_generation у индивидов? или достаточно history.add_to_history для свежесозданных индивидов?

2022-12-17 22:14 UTC, MorrisNein commented
> @MorrisNein глянь, пожалуйста, момент с добавлением в историю. надо ли там какие-то доп операции производить, например, с отметкой natural_generation у индивидов? или достаточно history.add_to_history для свежесозданных индивидов?

Выглядит ок. Да, задание поколения индивида происходит на стороне истории (точнее, класса "поколение").
Если будут возникать сомнения в реализации новых оптимизаторов, всегда можно прогнать их через этот тест:

https://github.com/ITMO-NSS-team/GOLEM/blob/add-other-optimizers/test/unit/optimizers/test_composing_history.py#L231-L255

2022-12-18 06:49 UTC, gkirgizov requested changes

2022-12-18 06:49 UTC, gkirgizov commented on golem/core/optimisers/random/random_search.py
> +        self.history.add_to_history([best_ind], 'final_choices')
best_ind не обновляется в ходе оптимизации

2022-12-18 06:49 UTC, gkirgizov commented on golem/core/optimisers/random/random_search.py
> +        self.history.add_to_history([best_ind], 'final_choices')
проверь другой оптимизатор тоже, чтобы история все-таки хранила лучшего

2022-12-18 08:53 UTC, gkirgizov requested changes

2022-12-18 08:53 UTC, gkirgizov commented on golem/core/optimisers/random/random_search.py
> +                    self.history.add_to_history([best_ind])
мы каждый раз добавляем в историю одно и то же?

2022-12-19 15:10 UTC, YamLyubov commented on examples/graph_model_optimization.py
> +            initial_graphs=initial)
[Привела](https://github.com/aimclub/GOLEM/pull/8/files#diff-b3e0dc9b191173cc647b7eec481026d8c44990fe1d2310511d9f9d5e9b114c2dR104-R110)

2022-12-19 15:16 UTC, YamLyubov commented on examples/graph_model_optimization.py
> +            initial_graphs=initial)
Пока что оставила while, так как переход к for подразумевает, что задано количество итераций, а это не всегда так. ```OptimizationParameters.num_of_generations```  может быть None. В таком случае оптимизация продолжается, пока не истечет таймаут, что довольно удобно, как мне кажется.

2022-12-19 15:17 UTC, YamLyubov commented on golem/core/optimisers/random/random_mutation_optimizer.py
> +            while not self.stop_optimization():
Пока что оставила while, так как переход к for подразумевает, что задано количество итераций, а это не всегда так. ```OptimizationParameters.num_of_generations``` может быть None. В таком случае оптимизация продолжается, пока не истечет таймаут, что довольно удобно, как мне кажется.

2022-12-19 15:29 UTC, YamLyubov commented on golem/core/optimisers/random_graph_factory.py
> +        pass
[Готово](RandomMutationSearchOptimizer)

2022-12-19 15:29 UTC, YamLyubov commented on golem/core/optimisers/random/random_search.py
> +    def _init_assumption(self, evaluator: EvaluationOperator) -> Tuple[Fitness, Individual]:
Я заметила, что в целом два оптимайзера очень похожи и сделала ```RandomSearchOptimizer``` базовым классом для ```RandomMutationSearchOptimizer```, так как последний класс имеет более специфичную функцию генерацию графа. Так у них теперь одна и та же функция используется.

2022-12-19 15:29 UTC, YamLyubov commented on golem/core/optimisers/random/random_mutation_optimizer.py
> +                mutation = Mutation(self.graph_optimizer_params, self.requirements, self.graph_generation_params)
Инициализацию мутации [вынесла](https://github.com/aimclub/GOLEM/pull/8/files#diff-03e5e52c72cd62ea6f1f5b57dbf9755193239bfb1e0b081a79a1291afbd8e2f0R27) в инит

2022-12-19 15:30 UTC, YamLyubov commented on golem/core/optimisers/random_graph_factory.py
> +            if choices([0, 1], weights=[0.7, 0.3])[0]:
[Готово](https://github.com/aimclub/GOLEM/pull/8/files#diff-7b7ace7ffcde980ee4ae31cd2ba552d387e7db349f42eadaf28a118524675055R57)

2022-12-19 15:35 UTC, YamLyubov commented on golem/core/optimisers/random/random_search.py
> +        self.history.add_to_history([best_ind], 'final_choices')
Так как поменяла код, больше не актуально

2022-12-19 15:36 UTC, YamLyubov commented on golem/core/optimisers/random/random_search.py
> +                    self.history.add_to_history([best_ind])
Изменила добавление в историю. Если лучший индивид не меняется, то он будет дублироваться, но такая же ситуация и с EvoGraphOptimizer

2022-12-20 08:27 UTC, YamLyubov commented on test/unit/optimizers/test_random_graph_factory.py
> +@pytest.mark.parametrize('max_depth', [1, 3, 5])
[Готово](https://github.com/aimclub/GOLEM/pull/8/files#diff-30dad9b62a5af7b5c20b8c09e67fa3804ce398e15e62b73931233c9174cd777fR14)

2022-12-20 08:31 UTC, YamLyubov commented on test/unit/optimizers/test_random_graph_factory.py
> +        assert graph.depth <= requirements.max_depth
Добавила [такое условие](https://github.com/aimclub/GOLEM/pull/8/files#diff-30dad9b62a5af7b5c20b8c09e67fa3804ce398e15e62b73931233c9174cd777fR34). Такая проверка не валит тест (по крайней мере валит его достаточно редко - при множестве запусков ни разу не упал) и не увеличивает время выполнения теста.

2022-12-20 08:32 UTC, YamLyubov commented on golem/core/optimisers/random_graph_factory.py
> +class DefaultRandomOptGraphFactory(BaseRandomOptGraphFactory):
[Сделано](https://github.com/aimclub/GOLEM/pull/8/files#diff-7b7ace7ffcde980ee4ae31cd2ba552d387e7db349f42eadaf28a118524675055R15-R16)

2022-12-20 10:15 UTC, gkirgizov requested changes

2022-12-20 10:15 UTC, gkirgizov commented on golem/core/optimisers/random_graph_factory.py
> +        graph_root = node_factory.get_node()
сделаешь в Fedot параллельный pull-request с этим?

2022-12-20 10:15 UTC, gkirgizov commented on requirements.txt
> +numpy>=1.16.*, <1.24.*
зачем такое ограничение? без веских причин лучше сверху версии не ограничивать. для "живых" проектов в активной разработке лучше поддержвать совместимость с последними версиями пакетов

2022-12-20 10:20 UTC, MorrisNein commented on requirements.txt
> +numpy>=1.16.*, <1.24.*
Тут на стороне seaborn проблема, он ещё не подстроился под новый  numpy

2022-12-20 10:26 UTC, MorrisNein commented on requirements.txt
> +numpy>=1.16.*, <1.24.*
Подсмотрел, в чём сыр-бор, в seaborn пишут, что это баг в numpy 1.24.0, и исключают только данную конкретную версию. Предлагаю поступить так же

https://github.com/mwaskom/seaborn/commit/26b3d0e29ff5286c32e6f934b2ed64cd20207496

2022-12-20 12:16 UTC, gkirgizov commented on requirements.txt
> +numpy>=1.16.*, <1.24.*
тогда != поставим

2022-12-20 14:29 UTC, gkirgizov approved these changes

2022-12-20 14:30 UTC, merged