Molecule search example
aimclub/GOLEM pull request #83
Opened 2023-04-17 14:54 UTC by YamLyubov

WIP

2023-05-10 16:35 UTC, gkirgizov commented
Первые мысли насчет экспериментов:
- после фикса #89 (в процессе) нужно будет запустить эксперименты еще раз
- на нескольких экспериментах построить графики изменения вероятностей мутаций (функция `plot_action_values`, пример построения графика в examples/adaptive_optimizer/experiment_setup.py)
- сравнить получающиеся вероятности мутаций с baseline из EvoMol (они приводят свои вероятности мутаций)
- плюс запустить GOLEM без бандита: (а) с равновероятными мутациями (б) со статичными вероятностями, равными таковым у EvoMol, добавить эти результаты в табличку

Пример графика: 
![ucb1_edges100_iter150_2min_actions](https://github.com/aimclub/GOLEM/assets/10994117/0fe14fa4-0d4c-40cb-9cbe-d09c8632ab35)

2023-05-11 06:16 UTC, gkirgizov requested changes

2023-05-11 06:16 UTC, gkirgizov commented on examples/molecule_search/guacamol_benchmark.py
> +            ],
Может, в файле с мутациями создать список `chemical_mutations`? Кажетс, они почти всегда все вместе будут использоваться. Импорты будут чуть проще

2023-05-11 09:48 UTC, YamLyubov commented on golem/visualisation/opt_viz_extra.py
> +        self.graph_visualizer = GraphVisualizer
Обнаружила, что это и сейчас не работает. Попробую сейчас посмотреть, если не получится исправить - заведу issue

2023-05-12 09:49 UTC, YamLyubov commented on examples/molecule_search/utils.py
> +    disconnected_graph = deepcopy(mol_graph.get_nx_graph())
Для мутаций перемещения/удаления функциональной группы сначала нужно составить список таких групп в молекуле. Для этого и нужна данная функция. Она возвращает вершины подграфа, который соединен с остальным графом только одним ребром (мостом). Для этого из графа удаляется вершина (inplace) и ищется связная компонента в получившемся графе.  Так как мы не хотим изначальный граф менять, нужно его скопировать

2023-05-12 13:53 UTC, YamLyubov commented on golem/core/optimisers/advisor.py
> +DomainStructureNode = TypeVar('DomainStructureNode')
[Done](https://github.com/aimclub/GOLEM/pull/83/files#diff-55452dbcaf948c4d0f4cfb6ea570d69db776d47b5c89dece473a5eafdb35b52fR17)

2023-05-12 13:54 UTC, YamLyubov commented on examples/molecule_search/mol_metrics.py
> +    qry_shingles = extract_shingles(molecule, radius, rooted)
[Оформила как класс ](https://github.com/aimclub/GOLEM/pull/83/files#diff-80a877a854dd4e49e8dca1d8d03563a8d6691a11cb3b712239142c7f1de47148R99-R107
)

2023-05-12 13:54 UTC, YamLyubov commented on examples/molecule_search/mol_metrics.py
> +    return db_shingles
Добавила [загрузку](https://github.com/aimclub/GOLEM/pull/83/files#diff-80a877a854dd4e49e8dca1d8d03563a8d6691a11cb3b712239142c7f1de47148R166-R169)

2023-05-12 13:55 UTC, YamLyubov commented on examples/molecule_search/utils.py
> +        largest_cycle_len = max(list(map(len, cycle_list)))
[Done ](https://github.com/aimclub/GOLEM/pull/83/files#diff-2bb1701e003750866d526ba5a46fa2a0762f608bc32cf396fc16a9c965a1aaaaR40
)

2023-05-12 13:55 UTC, YamLyubov commented on examples/molecule_search/guacamol_benchmark.py
> +            ],
[Done ](https://github.com/aimclub/GOLEM/pull/83/files#diff-26699697e6cb7a9cb439e6bb17a7c4972c0c3ff50490bf5e0ff12a424e0ce7daR165)

2023-05-12 15:54 UTC, gkirgizov commented
Кстати, а почему на Големовских графах в узлах не названия молекул, а номера?

2023-06-08 06:00 UTC, gkirgizov requested changes

2023-06-08 06:04 UTC, gkirgizov commented
Ах да, и добавь, пожалуйста, интеграционный тест на этот пример.

2023-06-08 13:45 UTC, YamLyubov commented on examples/molecule_search/utils.py
> +    disconnected_graph = deepcopy(mol_graph.get_nx_graph())
Да, действительно, можно и без deepcopy. [Убрала](https://github.com/aimclub/GOLEM/pull/83/files#diff-2bb1701e003750866d526ba5a46fa2a0762f608bc32cf396fc16a9c965a1aaaaR30)

2023-06-08 13:46 UTC, YamLyubov commented on golem/core/paths.py
> +        os.makedirs(save_path)
Не нужно, не знала, что так можно, заменила на `os.makedirs(..., exists_ok=True)`

2023-06-08 14:27 UTC, YamLyubov commented on golem/core/optimisers/opt_history_objects/opt_history.py
> +    def print_leaderboard(self, top_n: int = 10) -> str:
Меня смутило именно то, что возвращается строка, как будто ожидала от этого метода скорее список индиводов. Согласна, что `print_leaderboard` не очень удачное название, поменяла обратно))

2023-06-09 08:33 UTC, gkirgizov approved these changes

2023-06-09 10:07 UTC, merged