crossover for multi root graphs
aimclub/GOLEM pull request #84
Opened 2023-04-17 14:54 UTC by maypink

WIP

2023-04-19 07:16 UTC, gkirgizov requested changes

2023-04-19 07:16 UTC, gkirgizov commented on golem/core/optimisers/genetic/gp_operators.py
> +                    len(list(set(descriptive_id_recursive_nodes(node_second)))):
У меня есть подозрение, что ээтот код можно сильно ускорить, если перед началом проверки этих условий заранее вычислить recursive_id для всех нод. Это потребует одного обхода каждого графа. В данном же случае мы заново обходим подграфы каждый раз для вычисления этого id в условии.

Кстати, не пойму, почему не взять длину сразу от set: `len(set(...))`

2023-04-19 10:17 UTC, maypink commented on golem/core/optimisers/genetic/gp_operators.py
> +        def are_subtrees_the_same(match_set: List[Tuple[Any, Any]], node_first: Any, node_second: Any) -> bool:
ага, [вынесла](https://github.com/aimclub/GOLEM/pull/84/commits/c8017f2d1aa08a16e9818f24f84c87e3881aaefa#diff-673c5627acab141c1d8d1805637bb01069096052d94014e966309935dbe5b05dR68). энивэй эти функции выглядят достаточно полезными и для применения вне `equivalent_subtree`

2023-04-19 10:17 UTC, maypink commented on test/unit/optimizers/gp_operators/test_gp_operators.py
> +    for graphs, answers in zip(graphs_to_search_in, subgraphs_counts):
[йеп](https://github.com/aimclub/GOLEM/pull/84/commits/c8017f2d1aa08a16e9818f24f84c87e3881aaefa#diff-004cf753e415a18a40511f64c6dfa712f57c661f3aafc7f60260898618586f9bR61)

2023-04-20 16:33 UTC, gkirgizov approved these changes

2023-04-21 08:44 UTC, merged