Add Quick Start example to readme with several usability fixes
aimclub/GOLEM pull request #86
Opened 2023-04-19 05:32 UTC by gkirgizov

Changes:
- Add self-sufficient `simple_run.py` example with simple setup of Optimizer
- Objective can now be simple constructed from simple metric
- Default parameter changes (`max_arity=4, max_depth=10, early_stopping_iterations=50`)
- Default mutation set is changed to simple single-point mutations

Closes #48

2023-04-19 05:36 UTC, gkirgizov commented
Ppe8 issues for graph_search & tree_search are already fixed in parallel PR, so I ignore them to avoid conflicts

2023-04-19 10:39 UTC, nicl-nno commented on README_en.rst
> +            crossover_types=[CrossoverTypesEnum.subtree]
Мб лучше сделать quick start более лаконичным и не задавать мутации и кроссоверы вручную?

2023-04-19 10:45 UTC, maypink requested changes

2023-04-19 10:45 UTC, maypink commented on README.rst
> +Следующий пример показывает поиск графа по графу-эталону с помощью метрики расстояния редактирования (Edit Distance). Оптимизатор настраивается с минимальным набором параметров и простыми одноточечны
мб гиперссылки вставить на файлы с примерами? вроде их положение достаточно постоянно, не сломается через неделю

2023-04-24 05:40 UTC, gkirgizov commented on README_en.rst
> +            crossover_types=[CrossoverTypesEnum.subtree]
[сделал поменьше](https://github.com/aimclub/GOLEM/pull/86/commits/5d06a22505fd7db656a69aadf96d8f111ebf4ae5)

2023-04-24 05:40 UTC, gkirgizov commented on README.rst
> +Следующий пример показывает поиск графа по графу-эталону с помощью метрики расстояния редактирования (Edit Distance). Оптимизатор настраивается с минимальным набором параметров и простыми одноточечны
добавил

2023-04-24 07:30 UTC, nicl-nno approved these changes

2023-04-24 08:05 UTC, maypink approved these changes

2023-04-24 08:51 UTC, merged